# =============================================================================
# report/components.cmake — component / meta table
# =============================================================================

## @brief Join ids with `, ` (no quotes; `_bm_list_join` is for quoted lists).
## @param[in]  _items CMake list.
## @param[out] _out   Parent-scope string; empty if `_items` is empty.
function(_bm_report_join_ids _items _out)
	_bm_log_message(REPORT LOWLEVEL "Entering _bm_report_join_ids")
	set(_s "")
	set(_first TRUE)
	foreach(_it IN LISTS _items)
		if(_it STREQUAL "")
			continue()
		endif()
		if(_first)
			set(_s "${_it}")
			set(_first FALSE)
		else()
			string(APPEND _s ", ${_it}")
		endif()
	endforeach()
	set(${_out} "${_s}" PARENT_SCOPE)
	_bm_log_message(REPORT LOWLEVEL "Exiting _bm_report_join_ids")
endfunction()

## @brief Direct NEEDED BY list for `id` (inverse of `buildmaster_depend`).
## @param[in]  _id  Subject id (component or meta).
## @param[out] _out Parent-scope CMake list of component ids.
## @note One hop. Meta and group ids are omitted from the list.
function(_bm_report_needed_by _id _out)
	_bm_log_message(REPORT LOWLEVEL "Entering _bm_report_needed_by")
	set(_nb "")
	get_property(_srcs GLOBAL PROPERTY BUILDMASTER_COMPONENT_DEP_SOURCES)
	get_property(_dsts GLOBAL PROPERTY BUILDMASTER_COMPONENT_DEP_DESTS)
	get_property(_comps GLOBAL PROPERTY BUILDMASTER_COMPONENT_IDS)
	list(LENGTH _srcs _n)
	if(_n GREATER 0)
		math(EXPR _last "${_n} - 1")
		foreach(_i RANGE ${_last})
			list(GET _srcs ${_i} _s)
			list(GET _dsts ${_i} _d)
			if(NOT _d STREQUAL "${_id}")
				continue()
			endif()
			if(COMMAND _bm_group_is)
				_bm_group_is("${_s}" _sg)
				if(_sg)
					continue()
				endif()
			endif()
			_bm_meta_is("${_s}" _sm)
			if(_sm)
				continue()
			endif()
			if(_comps AND _s IN_LIST _comps)
				list(APPEND _nb "${_s}")
			endif()
		endforeach()
	endif()
	if(_nb)
		list(REMOVE_DUPLICATES _nb)
		list(SORT _nb)
	endif()
	set(${_out} "${_nb}" PARENT_SCOPE)
	_bm_log_message(REPORT LOWLEVEL "Exiting _bm_report_needed_by")
endfunction()

## @brief LINK column: graph link dests, meta members, plus raw LINK=.
## @param[in]  _id  Component or meta id.
## @param[out] _out Parent-scope display string, or `(none)`.
function(_bm_report_link_cell _id _out)
	_bm_log_message(REPORT LOWLEVEL "Entering _bm_report_link_cell")
	set(_items "")
	_bm_meta_is("${_id}" _is_meta)
	if(_is_meta)
		get_property(_items GLOBAL PROPERTY BUILDMASTER_META_${_id}_MEMBERS)
	else()
		get_property(_srcs GLOBAL PROPERTY BUILDMASTER_COMPONENT_LINK_SOURCES)
		get_property(_dsts GLOBAL PROPERTY BUILDMASTER_COMPONENT_LINK_DESTS)
		list(LENGTH _srcs _n)
		if(_n GREATER 0)
			math(EXPR _last "${_n} - 1")
			foreach(_i RANGE ${_last})
				list(GET _srcs ${_i} _s)
				list(GET _dsts ${_i} _d)
				if(_s STREQUAL "${_id}" AND NOT _d STREQUAL "")
					list(APPEND _items "${_d}")
				endif()
			endforeach()
		endif()
		get_property(_raw GLOBAL PROPERTY BUILDMASTER_COMPONENT_${_id}_LINK)
		foreach(_r IN LISTS _raw)
			if(NOT _r STREQUAL "")
				list(APPEND _items "${_r}")
			endif()
		endforeach()
	endif()
	if(_items)
		list(REMOVE_DUPLICATES _items)
	endif()
	_bm_report_join_ids("${_items}" _s)
	if(_s STREQUAL "")
		set(_s "(none)")
	endif()
	set(${_out} "${_s}" PARENT_SCOPE)
	_bm_log_message(REPORT LOWLEVEL "Exiting _bm_report_link_cell")
endfunction()

## @brief Extra C/C++ flags recorded on component OPTIONS (vs parent).
## @param[in]  _id    Component id.
## @param[in]  _which `C` or `CXX`.
## @param[out] _out   Parent-scope string (empty if none / unchanged).
function(_bm_report_langflags _id _which _out)
	_bm_log_message(REPORT LOWLEVEL "Entering _bm_report_langflags")
	set(_got "")
	get_property(_opts GLOBAL PROPERTY BUILDMASTER_COMPONENT_${_id}_OPTIONS)
	if(_which STREQUAL "CXX")
		set(_keys "-DCMAKE_CXX_FLAGS=;-Dcpp_args=")
		set(_parent "${CMAKE_CXX_FLAGS}")
	else()
		set(_keys "-DCMAKE_C_FLAGS=;-Dc_args=")
		set(_parent "${CMAKE_C_FLAGS}")
	endif()
	foreach(_tok IN LISTS _opts)
		foreach(_pfx IN LISTS _keys)
			string(LENGTH "${_pfx}" _pl)
			string(SUBSTRING "${_tok}" 0 ${_pl} _head)
			if(_head STREQUAL "${_pfx}")
				string(SUBSTRING "${_tok}" ${_pl} -1 _val)
				if(NOT _parent STREQUAL "")
					string(LENGTH "${_parent}" _parl)
					string(SUBSTRING "${_val}" 0 ${_parl} _ph)
					if(_ph STREQUAL "${_parent}")
						string(SUBSTRING "${_val}" ${_parl} -1 _val)
					endif()
				endif()
				string(STRIP "${_val}" _val)
				if(NOT _val STREQUAL "")
					set(_got "${_val}")
				endif()
			endif()
		endforeach()
	endforeach()
	set(${_out} "${_got}" PARENT_SCOPE)
	_bm_log_message(REPORT LOWLEVEL "Exiting _bm_report_langflags")
endfunction()

## @brief FILES child text (`name (unpack)`).
## @param[in]  _id  Component id.
## @param[out] _out Parent-scope string (empty if no FILES groups).
function(_bm_report_files_line _id _out)
	_bm_log_message(REPORT LOWLEVEL "Entering _bm_report_files_line")
	set(_bits "")
	get_property(_names GLOBAL PROPERTY BUILDMASTER_COMPONENT_${_id}_FILES_NAMES)
	get_property(_unp GLOBAL PROPERTY BUILDMASTER_COMPONENT_${_id}_FILES_UNPACKS)
	list(LENGTH _names _n)
	if(_n GREATER 0)
		math(EXPR _last "${_n} - 1")
		foreach(_i RANGE ${_last})
			list(GET _names ${_i} _nm)
			set(_u FALSE)
			if(_unp)
				list(LENGTH _unp _un)
				if(_i LESS _un)
					list(GET _unp ${_i} _u)
				endif()
			endif()
			if(_u)
				list(APPEND _bits "${_nm} (unpack)")
			elseif(NOT _nm STREQUAL "")
				list(APPEND _bits "${_nm}")
			endif()
		endforeach()
	endif()
	_bm_report_join_ids("${_bits}" _s)
	set(${_out} "${_s}" PARENT_SCOPE)
	_bm_log_message(REPORT LOWLEVEL "Exiting _bm_report_files_line")
endfunction()

## @brief LINKFLAGS children: one line per OPTSTR token / leftover flag.
## @param[in] _id    Component id.
## @param[in] _key_w Child key width.
function(_bm_report_linkflags_lines _id _key_w)
	_bm_log_message(REPORT LOWLEVEL "Entering _bm_report_linkflags_lines")
	set(_shown FALSE)
	get_property(_optstr GLOBAL PROPERTY BUILDMASTER_COMPONENT_${_id}_OPTSTR)
	if(NOT _optstr STREQUAL "")
		_bm_opt_split_pairs("${_optstr}" _pairs)
		foreach(_p IN LISTS _pairs)
			_bm_opt_split_pair("${_p}" _k _v _ok)
			if(_ok AND _k STREQUAL "LINKFLAGS")
				if(_v MATCHES "^\\{(.*)\\}$")
					_bm_opt_split_pairs("${CMAKE_MATCH_1}" _inner)
					foreach(_in IN LISTS _inner)
						if(NOT _in STREQUAL "")
							_bm_report_child("LINKFLAGS" "${_in}" "${_key_w}" 3)
							set(_shown TRUE)
						endif()
					endforeach()
				elseif(NOT _v STREQUAL "")
					_bm_report_child("LINKFLAGS" "${_v}" "${_key_w}" 3)
					set(_shown TRUE)
				endif()
			endif()
		endforeach()
	endif()
	if(NOT _shown)
		get_property(_lf GLOBAL PROPERTY BUILDMASTER_COMPONENT_${_id}_LINKFLAGS)
		foreach(_f IN LISTS _lf)
			if(NOT _f STREQUAL "")
				_bm_report_child("LINKFLAGS" "${_f}" "${_key_w}" 3)
			endif()
		endforeach()
	endif()
	_bm_log_message(REPORT LOWLEVEL "Exiting _bm_report_linkflags_lines")
endfunction()

## @brief One component or meta row plus child overrides.
## @param[in] _id    Registered id (not a group).
## @param[in] _idw   ID column width.
## @param[in] _typew TYPE column width.
## @param[in] _key_w Child-key column width.
function(_bm_report_one _id _idw _typew _key_w)
	_bm_log_message(REPORT LOWLEVEL "Entering _bm_report_one")
	_bm_report_type_label("${_id}" _type)
	_bm_report_link_cell("${_id}" _link)
	_bm_report_pad("${_id}" "${_idw}" _idcell)
	_bm_report_pad("${_type}" "${_typew}" _tcell)
	_bm_log_message(REPORT STATUS "${_idcell}${_tcell}${_link}" 2)

	_bm_report_needed_by("${_id}" _nb)
	_bm_report_join_ids("${_nb}" _nbs)
	_bm_report_child("NEEDED BY" "${_nbs}" "${_key_w}" 3)

	_bm_meta_is("${_id}" _is_meta)
	if(_is_meta)
		get_property(_tc GLOBAL PROPERTY BUILDMASTER_META_${_id}_TOOLCHAIN)
		get_property(_repack GLOBAL PROPERTY BUILDMASTER_META_${_id}_REPACK)
		if(NOT _tc STREQUAL "")
			_bm_report_child("TOOLCHAIN" "${_tc}" "${_key_w}" 3)
		endif()
		if(_repack)
			_bm_report_child("REPACK" "yes" "${_key_w}" 3)
		endif()
		_bm_log_message(REPORT LOWLEVEL "Exiting _bm_report_one")
		return()
	endif()

	_bm_tc_stored("${_id}" _tc)
	if(NOT _tc STREQUAL "")
		_bm_report_child("TOOLCHAIN" "${_tc}" "${_key_w}" 3)
	endif()
	get_property(_bo GLOBAL PROPERTY BUILDMASTER_COMPONENT_${_id}_BUILDONLY)
	if(_bo)
		_bm_report_child("BUILDONLY" "yes" "${_key_w}" 3)
	endif()
	_bm_report_langflags("${_id}" C _cf)
	_bm_report_child("CFLAGS" "${_cf}" "${_key_w}" 3)
	_bm_report_langflags("${_id}" CXX _cxxf)
	_bm_report_child("CXXFLAGS" "${_cxxf}" "${_key_w}" 3)
	_bm_report_files_line("${_id}" _files)
	_bm_report_child("FILES" "${_files}" "${_key_w}" 3)
	_bm_report_linkflags_lines("${_id}" "${_key_w}")

	_bm_log_message(REPORT LOWLEVEL "Exiting _bm_report_one")
endfunction()

## @brief Components + metas, alphabetical by id. Groups omitted.
## @note Sort is for reading. It is not graph order, group-walk order,
##       or configure order.
function(_bm_report_components)
	_bm_log_message(REPORT LOWLEVEL "Entering _bm_report_components")
	_bm_log_message(REPORT STATUS "Components" 1)

	get_property(_comps GLOBAL PROPERTY BUILDMASTER_COMPONENT_IDS)
	get_property(_metas GLOBAL PROPERTY BUILDMASTER_META_IDS)
	set(_ids "")
	foreach(_id IN LISTS _comps _metas)
		if(_id STREQUAL "")
			continue()
		endif()
		if(COMMAND _bm_group_is)
			_bm_group_is("${_id}" _g)
			if(_g)
				continue()
			endif()
		endif()
		list(APPEND _ids "${_id}")
	endforeach()
	if(NOT _ids)
		_bm_log_message(REPORT STATUS "(none)" 2)
		_bm_log_message(REPORT LOWLEVEL "Exiting _bm_report_components")
		return()
	endif()
	list(REMOVE_DUPLICATES _ids)
	list(SORT _ids)

	set(_types "")
	foreach(_id IN LISTS _ids)
		_bm_report_type_label("${_id}" _ty)
		list(APPEND _types "${_ty}")
	endforeach()
	_bm_report_max_len("${_ids}" _idw)
	_bm_report_max_len("${_types}" _typew)
	math(EXPR _idw "${_idw} + 2")
	math(EXPR _typew "${_typew} + 2")

	_bm_report_pad("ID" "${_idw}" _h1)
	_bm_report_pad("TYPE" "${_typew}" _h2)
	_bm_log_message(REPORT STATUS "${_h1}${_h2}LINK" 2)

	set(_key_w 16)
	foreach(_id IN LISTS _ids)
		_bm_report_one("${_id}" "${_idw}" "${_typew}" "${_key_w}")
	endforeach()

	_bm_log_message(REPORT LOWLEVEL "Exiting _bm_report_components")
endfunction()
