if(NOT BUILDMASTER_CONFIGURED)
	set(BUILDMASTER_SRCDIR "${CMAKE_CURRENT_LIST_DIR}")
	set(BUILDMASTER_BINDIR "${CMAKE_CURRENT_BINARY_DIR}")
	set(BUILDMASTER_SCRIPTSDIR "${BUILDMASTER_BINDIR}/scripts")
	if(DEFINED ENV{BUILDMASTER_DOWNLOADSDIR})
		set(BUILDMASTER_DOWNLOADSDIR "$ENV{BUILDMASTER_DOWNLOADSDIR}")
	else()
		set(BUILDMASTER_DOWNLOADSDIR "${BUILDMASTER_BINDIR}/downloads")
	endif()
	set(BUILDMASTER_TOOLCHAIN_FILE "${BUILDMASTER_SCRIPTSDIR}/toolchain.cmake")
	set(BUILDMASTER_INSTALL_DIR "${CMAKE_CURRENT_BINARY_DIR}/install")
	set(BUILDMASTER_INSTALL_LIBDIR "${BUILDMASTER_INSTALL_DIR}/${CMAKE_INSTALL_LIBDIR}")
	set(BUILDMASTER_INSTALL_BINDIR "${BUILDMASTER_INSTALL_DIR}/${CMAKE_INSTALL_BINDIR}")
	set(BUILDMASTER_INSTALL_INCLUDEDIR "${BUILDMASTER_INSTALL_DIR}/${CMAKE_INSTALL_INCLUDEDIR}")
	file(MAKE_DIRECTORY "${BUILDMASTER_SCRIPTSDIR}")
	file(MAKE_DIRECTORY "${BUILDMASTER_DOWNLOADSDIR}")
	file(MAKE_DIRECTORY "${BUILDMASTER_INSTALL_DIR}")
	file(MAKE_DIRECTORY "${BUILDMASTER_INSTALL_LIBDIR}")
	file(MAKE_DIRECTORY "${BUILDMASTER_INSTALL_BINDIR}")
	file(MAKE_DIRECTORY "${BUILDMASTER_INSTALL_INCLUDEDIR}")
	set(PATH "${BUILDMASTER_INSTALL_BINDIR}")

	# Enable/Disable debug
	if(DEFINED ENV{BUILDMASTER_DEBUG} AND "$ENV{BUILDMASTER_DEBUG}" STREQUAL "1")
		set(BUILDMASTER_DEBUG ON)
	else()
		set(BUILDMASTER_DEBUG OFF)
	endif()

	# Verbose compile only (cmake --build / meson compile). DEBUG does not imply VERBOSE.
	if(DEFINED ENV{BUILDMASTER_VERBOSE} AND "$ENV{BUILDMASTER_VERBOSE}" STREQUAL "1")
		set(BUILDMASTER_VERBOSE ON)
	elseif(BUILDMASTER_VERBOSE)
		# honour -DBUILDMASTER_VERBOSE=ON from the command line
		set(BUILDMASTER_VERBOSE ON)
	else()
		set(BUILDMASTER_VERBOSE OFF)
	endif()

	# Fail-fast: after a stage failure, subsequent stages can skip (see markers/).
	# Truthy ENV: 1, ON, TRUE, YES (case-insensitive). Default OFF (cache warming).
	if(DEFINED ENV{BUILDMASTER_FAIL_FAST})
		string(TOUPPER "$ENV{BUILDMASTER_FAIL_FAST}" _BUILDMASTER_FF)
		if(_BUILDMASTER_FF STREQUAL "1"
				OR _BUILDMASTER_FF STREQUAL "ON"
				OR _BUILDMASTER_FF STREQUAL "TRUE"
				OR _BUILDMASTER_FF STREQUAL "YES")
			set(BUILDMASTER_FAIL_FAST ON)
		else()
			set(BUILDMASTER_FAIL_FAST OFF)
		endif()
		unset(_BUILDMASTER_FF)
	elseif(BUILDMASTER_FAIL_FAST)
		set(BUILDMASTER_FAIL_FAST ON)
	else()
		set(BUILDMASTER_FAIL_FAST OFF)
	endif()

	set(BUILDMASTER_MARKERS_DIR "${BUILDMASTER_BINDIR}/markers")
	set(BUILDMASTER_FAIL_MARKER "${BUILDMASTER_MARKERS_DIR}/buildmaster.failed")
	file(MAKE_DIRECTORY "${BUILDMASTER_MARKERS_DIR}")

	# Reset fail markers at the start of every parent build (ninja/make/cmake --build).
	# Created only on first bootstrap so nested BuildMaster does not redefine the target.
	if(NOT TARGET buildmaster_build_init)
		add_custom_target(buildmaster_build_init
			COMMAND ${CMAKE_COMMAND} -E rm -rf "${BUILDMASTER_MARKERS_DIR}"
			COMMAND ${CMAKE_COMMAND} -E make_directory "${BUILDMASTER_MARKERS_DIR}"
			COMMENT "BuildMaster: reset fail markers"
			VERBATIM
		)
	endif()

	# Update out part of the toolchain file
	include("${CMAKE_CURRENT_LIST_DIR}/update_toolchain.cmake")
endif()
