if(NOT BUILDMASTER_CONFIGURED)
	set(BUILDMASTER_SRCDIR "${CMAKE_CURRENT_LIST_DIR}")
	set(BUILDMASTER_BINDIR "${CMAKE_CURRENT_BINARY_DIR}")
	set(BUILDMASTER_SCRIPTSDIR "${BUILDMASTER_BINDIR}/scripts")
	# ENV paths on Windows often use backslashes; CMake treats \U \t \n etc. as
	# escapes when the value is written to toolchain.cmake or expanded in strings.
	if(DEFINED ENV{BUILDMASTER_DOWNLOADSDIR} AND NOT "$ENV{BUILDMASTER_DOWNLOADSDIR}" STREQUAL "")
		file(TO_CMAKE_PATH "$ENV{BUILDMASTER_DOWNLOADSDIR}" BUILDMASTER_DOWNLOADSDIR)
	else()
		set(BUILDMASTER_DOWNLOADSDIR "${BUILDMASTER_BINDIR}/downloads")
	endif()
	set(BUILDMASTER_TOOLCHAIN_FILE "${BUILDMASTER_SCRIPTSDIR}/toolchain.cmake")
	set(BUILDMASTER_INSTALL_DIR "${CMAKE_CURRENT_BINARY_DIR}/install")
	set(BUILDMASTER_INSTALL_LIBDIR "${BUILDMASTER_INSTALL_DIR}/${CMAKE_INSTALL_LIBDIR}")
	set(BUILDMASTER_INSTALL_BINDIR "${BUILDMASTER_INSTALL_DIR}/${CMAKE_INSTALL_BINDIR}")
	set(BUILDMASTER_INSTALL_INCLUDEDIR "${BUILDMASTER_INSTALL_DIR}/${CMAKE_INSTALL_INCLUDEDIR}")
	file(MAKE_DIRECTORY "${BUILDMASTER_SCRIPTSDIR}")
	file(MAKE_DIRECTORY "${BUILDMASTER_DOWNLOADSDIR}")
	file(MAKE_DIRECTORY "${BUILDMASTER_INSTALL_DIR}")
	file(MAKE_DIRECTORY "${BUILDMASTER_INSTALL_LIBDIR}")
	file(MAKE_DIRECTORY "${BUILDMASTER_INSTALL_BINDIR}")
	file(MAKE_DIRECTORY "${BUILDMASTER_INSTALL_INCLUDEDIR}")
	set(PATH "${BUILDMASTER_INSTALL_BINDIR}")

	if(DEFINED ENV{BUILDMASTER_DEBUG} AND "$ENV{BUILDMASTER_DEBUG}" STREQUAL "1")
		set(BUILDMASTER_DEBUG ON)
	else()
		set(BUILDMASTER_DEBUG OFF)
	endif()

	if(DEFINED ENV{BUILDMASTER_VERBOSE} AND "$ENV{BUILDMASTER_VERBOSE}" STREQUAL "1")
		set(BUILDMASTER_VERBOSE ON)
	elseif(BUILDMASTER_VERBOSE)
		set(BUILDMASTER_VERBOSE ON)
	else()
		set(BUILDMASTER_VERBOSE OFF)
	endif()

	if(DEFINED ENV{BUILDMASTER_FAIL_FAST})
		string(TOUPPER "$ENV{BUILDMASTER_FAIL_FAST}" _BUILDMASTER_FF)
		if(_BUILDMASTER_FF STREQUAL "1"
				OR _BUILDMASTER_FF STREQUAL "ON"
				OR _BUILDMASTER_FF STREQUAL "TRUE"
				OR _BUILDMASTER_FF STREQUAL "YES")
			set(BUILDMASTER_FAIL_FAST ON)
		else()
			set(BUILDMASTER_FAIL_FAST OFF)
		endif()
		unset(_BUILDMASTER_FF)
	elseif(BUILDMASTER_FAIL_FAST)
		set(BUILDMASTER_FAIL_FAST ON)
	else()
		set(BUILDMASTER_FAIL_FAST OFF)
	endif()

	# BUILDMASTER_CLEAN_RESET_REPOS — default ON
	if(DEFINED ENV{BUILDMASTER_CLEAN_RESET_REPOS})
		string(TOUPPER "$ENV{BUILDMASTER_CLEAN_RESET_REPOS}" _BM_CRR)
		if(_BM_CRR STREQUAL "0"
				OR _BM_CRR STREQUAL "OFF"
				OR _BM_CRR STREQUAL "FALSE"
				OR _BM_CRR STREQUAL "NO"
				OR _BM_CRR STREQUAL "")
			set(BUILDMASTER_CLEAN_RESET_REPOS OFF)
		else()
			set(BUILDMASTER_CLEAN_RESET_REPOS ON)
		endif()
		unset(_BM_CRR)
	else()
		set(BUILDMASTER_CLEAN_RESET_REPOS ON)
	endif()

	set(BUILDMASTER_MARKERS_DIR "${BUILDMASTER_BINDIR}/markers")
	set(BUILDMASTER_FAIL_MARKER "${BUILDMASTER_MARKERS_DIR}/buildmaster.failed")
	file(MAKE_DIRECTORY "${BUILDMASTER_MARKERS_DIR}")

	# If this stamp is removed (buildmaster_clean), the next cmake --build
	# re-runs parent configure via CMAKE_CONFIGURE_DEPENDS so include(git)
	# scripts run again at configure time.
	set(BUILDMASTER_GIT_CONFIGURE_STAMP "${BUILDMASTER_SCRIPTSDIR}/git_configure.stamp")
	file(WRITE "${BUILDMASTER_GIT_CONFIGURE_STAMP}" "BuildMaster git configure stamp\n")
	set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS
		"${BUILDMASTER_GIT_CONFIGURE_STAMP}")

	if(NOT TARGET buildmaster_build_init)
		add_custom_target(buildmaster_build_init
			COMMAND ${CMAKE_COMMAND} -E rm -rf "${BUILDMASTER_MARKERS_DIR}"
			COMMAND ${CMAKE_COMMAND} -E make_directory "${BUILDMASTER_MARKERS_DIR}"
			COMMENT "BuildMaster: reset fail markers"
			VERBATIM
		)
	endif()

	# Toolchain dump is registered via buildmaster_toolchain_export* and written
	# once at the end of the root CMakeLists.txt (buildmaster_toolchain_write).
endif()
