include("${CMAKE_CURRENT_LIST_DIR}/../../../log.cmake")
if(COMMAND buildmaster_loglevel_init)
	buildmaster_loglevel_init()
endif()

set(_bm_edge_list "${BM_TEST_EXPECTED_DIR}/dependant_edges.txt")
if(NOT EXISTS "${_bm_edge_list}")
	_bm_log_message(CORE FATAL "Missing ${_bm_edge_list}")
endif()

set(_bm_fail FALSE)
set(_bm_edge_count 0)

file(STRINGS "${_bm_edge_list}" _bm_lines)
foreach(_line IN LISTS _bm_lines)
	string(STRIP "${_line}" _line)
	if(_line STREQUAL "" OR _line MATCHES "^#")
		continue()
	endif()

	if(NOT _line MATCHES "->")
		_bm_log_message(CORE WARNING "Malformed edge line: ${_line}")
		continue()
	endif()

	string(REPLACE "->" ";" _parts "${_line}")
	list(GET _parts 0 _from)
	list(GET _parts 1 _to)
	string(STRIP "${_from}" _from)
	string(STRIP "${_to}" _to)

	if(NOT TARGET ${_from})
		_bm_log_message(CORE WARNING "Edge: dependent target '${_from}' does not exist")
		set(_bm_fail TRUE)
		continue()
	endif()
	if(NOT TARGET ${_to})
		_bm_log_message(CORE WARNING "Edge: prerequisite target '${_to}' does not exist")
		set(_bm_fail TRUE)
		continue()
	endif()

	get_target_property(_deps ${_from} MANUALLY_ADDED_DEPENDENCIES)
	if(_deps STREQUAL "_deps-NOTFOUND" OR NOT _deps)
		set(_deps "")
	endif()

	list(FIND _deps "${_to}" _idx)
	if(_idx EQUAL -1)
		_bm_log_message(CORE WARNING "Edge missing: ${_from} -> ${_to} (have: ${_deps})")
		set(_bm_fail TRUE)
	else()
		math(EXPR _bm_edge_count "${_bm_edge_count} + 1")
	endif()
endforeach()

if(_bm_fail)
	_bm_log_message(CORE FATAL "dependant edge checks failed")
endif()

_bm_log_message(CORE STATUS "dependant edges: OK (${_bm_edge_count} checked)")
