include("${CMAKE_CURRENT_LIST_DIR}/../../../log.cmake")
if(COMMAND buildmaster_loglevel_init)
	buildmaster_loglevel_init()
endif()

function(_bm_lf_has opts token out_var)
	set(_hit FALSE)
	foreach(_it IN LISTS opts)
		if(_it STREQUAL "${token}")
			set(_hit TRUE)
			break()
		endif()
	endforeach()
	set(${out_var} "${_hit}" PARENT_SCOPE)
endfunction()

function(_bm_lf_expect tgt token should_have)
	if(NOT TARGET "${tgt}")
		buildmaster_message(CORE FATAL "LINKFLAGS check: target '${tgt}' does not exist")
	endif()
	get_target_property(_opts "${tgt}" INTERFACE_LINK_OPTIONS)
	if(_opts STREQUAL "_opts-NOTFOUND" OR NOT _opts)
		set(_opts "")
	endif()
	_bm_lf_has("${_opts}" "${token}" _has)
	if(should_have AND NOT _has)
		buildmaster_message(CORE FATAL
			"LINKFLAGS: '${tgt}' missing '${token}' (have: ${_opts})")
	endif()
	if(NOT should_have AND _has)
		buildmaster_message(CORE FATAL
			"LINKFLAGS: '${tgt}' must not carry '${token}' on this host (have: ${_opts})")
	endif()
endfunction()

foreach(_t lf-os lf-unix lf-os-meta lf-unix-meta)
	if(NOT TARGET "${_t}")
		buildmaster_message(CORE FATAL "LINKFLAGS fixture '${_t}' was not materialized")
	endif()
endforeach()

set(_win "/ALTERNATENAME:bm_lf_ok=__ImageBase")
set(_linux "-Wl,--defsym,bm_lf_ok=1")
set(_mac "-Wl,-alias,__mh_execute_header,_bm_lf_ok")
set(_unix "-Wl,-rpath,/bm-harness-unix")

if(WIN32)
	_bm_lf_expect(lf-os "${_win}" TRUE)
	_bm_lf_expect(lf-os "${_linux}" FALSE)
	_bm_lf_expect(lf-os "${_mac}" FALSE)
	_bm_lf_expect(lf-os "${_unix}" FALSE)
	_bm_lf_expect(lf-os-meta "${_win}" TRUE)
	_bm_lf_expect(lf-unix "${_unix}" FALSE)
	_bm_lf_expect(lf-unix "${_win}" FALSE)
	_bm_lf_expect(lf-unix-meta "${_unix}" FALSE)
elseif(APPLE)
	_bm_lf_expect(lf-os "${_win}" FALSE)
	_bm_lf_expect(lf-os "${_linux}" FALSE)
	_bm_lf_expect(lf-os "${_mac}" TRUE)
	_bm_lf_expect(lf-os "${_unix}" FALSE)
	_bm_lf_expect(lf-os-meta "${_mac}" TRUE)
	_bm_lf_expect(lf-unix "${_unix}" TRUE)
	_bm_lf_expect(lf-unix "${_mac}" FALSE)
	_bm_lf_expect(lf-unix-meta "${_unix}" TRUE)
elseif(CMAKE_SYSTEM_NAME STREQUAL "Linux")
	_bm_lf_expect(lf-os "${_win}" FALSE)
	_bm_lf_expect(lf-os "${_linux}" TRUE)
	_bm_lf_expect(lf-os "${_mac}" FALSE)
	_bm_lf_expect(lf-os "${_unix}" FALSE)
	_bm_lf_expect(lf-os-meta "${_linux}" TRUE)
	_bm_lf_expect(lf-unix "${_unix}" TRUE)
	_bm_lf_expect(lf-unix "${_linux}" FALSE)
	_bm_lf_expect(lf-unix-meta "${_unix}" TRUE)
else()
	buildmaster_message(CORE FATAL
		"LINKFLAGS check: unhandled CMAKE_SYSTEM_NAME '${CMAKE_SYSTEM_NAME}'")
endif()

buildmaster_message(CORE STATUS "LINKFLAGS groups: OK (${CMAKE_SYSTEM_NAME})")
