set(_bm_var_list "${BM_TEST_EXPECTED_DIR}/propagated_vars.txt")
if(NOT EXISTS "${_bm_var_list}")
	message(FATAL_ERROR "Missing ${_bm_var_list}")
endif()

if(WIN32)
	set(_bm_plat windows)
else()
	set(_bm_plat unix)
endif()

set(_bm_fail FALSE)
file(STRINGS "${_bm_var_list}" _bm_lines)
foreach(_line IN LISTS _bm_lines)
	string(STRIP "${_line}" _line)
	if(_line STREQUAL "" OR _line MATCHES "^#")
		continue()
	endif()

	string(REPLACE "|" ";" _parts "${_line}")
	list(LENGTH _parts _n)
	if(_n LESS 3)
		message(WARNING "Malformed propagation line: ${_line}")
		continue()
	endif()

	list(GET _parts 0 _var)
	list(GET _parts 1 _policy)
	list(GET _parts 2 _scope)

	if(NOT _scope STREQUAL "all" AND NOT _scope STREQUAL "${_bm_plat}")
		continue()
	endif()

	if(NOT DEFINED ${_var})
		message(SEND_ERROR "Propagation: '${_var}' is not defined")
		set(_bm_fail TRUE)
		continue()
	endif()

	if(_policy STREQUAL "required" OR _policy STREQUAL "file")
		if("${${_var}}" STREQUAL "")
			message(SEND_ERROR "Propagation: '${_var}' is empty (policy ${_policy})")
			set(_bm_fail TRUE)
			continue()
		endif()
	endif()

	if(_policy STREQUAL "file")
		if(NOT EXISTS "${${_var}}")
			message(SEND_ERROR "Propagation: '${_var}' path does not exist: ${${_var}}")
			set(_bm_fail TRUE)
		endif()
	endif()
endforeach()

if(_bm_fail)
	message(FATAL_ERROR "BuildMaster propagation checks failed")
endif()

message(STATUS "BuildMaster propagation: OK")