include("${CMAKE_CURRENT_LIST_DIR}/../../../log.cmake")
if(COMMAND buildmaster_loglevel_init)
	buildmaster_loglevel_init()
endif()

set(_bm_api_list "${BM_TEST_EXPECTED_DIR}/public_functions.txt")
if(NOT EXISTS "${_bm_api_list}")
	buildmaster_message(CORE FATAL "Missing ${_bm_api_list}")
endif()

file(STRINGS "${_bm_api_list}" _bm_lines)
set(_bm_missing "")
foreach(_line IN LISTS _bm_lines)
	string(STRIP "${_line}" _line)
	if(_line STREQUAL "" OR _line MATCHES "^#")
		continue()
	endif()
	if(NOT COMMAND ${_line})
		list(APPEND _bm_missing "${_line}")
	endif()
endforeach()

if(_bm_missing)
	list(JOIN _bm_missing ", " _msg)
	buildmaster_message(CORE FATAL "API missing commands: ${_msg}")
endif()

buildmaster_message(CORE STATUS "API: all public commands present")
