if(NOT TARGET raw-lib)
    message(FATAL_ERROR "link-raw: target raw-lib missing")
endif()
get_target_property(_libs raw-lib INTERFACE_LINK_LIBRARIES)
if(NOT _libs)
    set(_libs "")
endif()
if(WIN32)
    set(_want "kernel32")
else()
    set(_want "m")
endif()
string(FIND "${_libs}" "${_want}" _pos)
if(_pos LESS 0)
    message(FATAL_ERROR
        "link-raw: INTERFACE_LINK_LIBRARIES of raw-lib lacks '${_want}': ${_libs}")
endif()
message(STATUS "[BuildMaster/Core     ]: raw LINK=${_want} on raw-lib")
