_bm_tc_export(BUILDMASTER_TOOLS_NINJA_SRCDIR "${BUILDMASTER_TOOLS_NINJA_SRCDIR}")
_bm_tc_export_raw("set(ENV_NINJA_COMMAND ${ENV_NINJA_COMMAND})")
_bm_tc_export_raw("set(ENV_NINJA_SILENT_COMMAND ${ENV_NINJA_SILENT_COMMAND})")
