cmake_minimum_required(VERSION 3.20)
project(exeleaflib LANGUAGES C)
include(GNUInstallDirs)
add_library(exeleaflib STATIC lib.c)
target_include_directories(exeleaflib PUBLIC ${CMAKE_CURRENT_SOURCE_DIR})
install(TARGETS exeleaflib ARCHIVE DESTINATION ${CMAKE_INSTALL_LIBDIR})
install(FILES lib.h DESTINATION ${CMAKE_INSTALL_INCLUDEDIR})