set(BUILDMASTER_TOOLS_CMAKE_SRC_DIR "${CMAKE_CURRENT_LIST_DIR}")
set(BUILDMASTER_SCRIPTS_CMAKE_DIR "${BUILDMASTER_SCRIPTS_DIR}/cmake")
file(MAKE_DIRECTORY "${BUILDMASTER_SCRIPTS_CMAKE_DIR}")
get_filename_component(CMAKE_EXECUTABLE "${CMAKE_COMMAND}" NAME)
set(_env_cmake_list "${ENV_RUNNER} ${CMAKE_EXECUTABLE}")
set(_env_cmake_silent_list "${ENV_RUNNER_SILENT} ${CMAKE_EXECUTABLE}")
prepare_command(ENV_CMAKE_COMMAND "${_env_cmake_list}")
prepare_command(ENV_CMAKE_SILENT_COMMAND "${_env_cmake_silent_list}")