if(NOT BUILDMASTER_TOOLS_CMAKE_SRCDIR)
	set(BUILDMASTER_TOOLS_CMAKE_SRCDIR "${CMAKE_CURRENT_LIST_DIR}" CACHE INTERNAL
		"tools/cmake source dir")
	set(BUILDMASTER_SCRIPTS_CMAKEDIR "${BUILDMASTER_SCRIPTSDIR}/cmake" CACHE INTERNAL
		"Generated cmake-tool scripts")
	file(MAKE_DIRECTORY "${BUILDMASTER_SCRIPTS_CMAKEDIR}")
	get_filename_component(CMAKE_EXECUTABLE "${CMAKE_COMMAND}" NAME)
	set(_env_cmake_list "${ENV_RUNNER} ${CMAKE_EXECUTABLE}")
	set(_env_cmake_silent_list "${ENV_RUNNER_SILENT} ${CMAKE_EXECUTABLE}")
	set(_env_cmake_compile_list "${ENV_RUNNER_COMPILE} ${CMAKE_EXECUTABLE}")
	_bm_env_prepare_command(ENV_CMAKE_COMMAND "${_env_cmake_list}")
	_bm_env_prepare_command(ENV_CMAKE_SILENT_COMMAND "${_env_cmake_silent_list}")
	_bm_env_prepare_command(ENV_CMAKE_COMPILE_COMMAND "${_env_cmake_compile_list}")
	set(ENV_CMAKE_COMMAND "${ENV_CMAKE_COMMAND}" CACHE INTERNAL "")
	set(ENV_CMAKE_SILENT_COMMAND "${ENV_CMAKE_SILENT_COMMAND}" CACHE INTERNAL "")
	set(ENV_CMAKE_COMPILE_COMMAND "${ENV_CMAKE_COMPILE_COMMAND}" CACHE INTERNAL "")

	if(NOT BUILDMASTER_INSTALL_DIR)
		_bm_log_message(CMAKE FATAL
			"tools/cmake: BUILDMASTER_INSTALL_DIR is empty — bootstrap is broken")
	endif()
	_bm_path_normalize(_bm_prefix "${BUILDMASTER_INSTALL_DIR}")
	if(NOT CMAKE_PREFIX_PATH)
		set(CMAKE_PREFIX_PATH "${_bm_prefix}")
	else()
		list(FIND CMAKE_PREFIX_PATH "${_bm_prefix}" _bm_pfx_i)
		if(_bm_pfx_i EQUAL -1)
			set(CMAKE_PREFIX_PATH "${_bm_prefix};${CMAKE_PREFIX_PATH}")
		endif()
	endif()
	set(CMAKE_PREFIX_PATH "${CMAKE_PREFIX_PATH}" CACHE STRING
		"BuildMaster install prefix first" FORCE)

	include("${CMAKE_CURRENT_LIST_DIR}/update_toolchain.cmake")
endif()
