set(BUILDMASTER_TOOLS_CMAKE_SRC_DIR "${BUILDMASTER_TOOLS_CMAKE_SRC_DIR}" PARENT_SCOPE)
set(BUILDMASTER_SCRIPTS_CMAKE_DIR "${BUILDMASTER_SCRIPTS_CMAKE_DIR}" PARENT_SCOPE)
set(ENV_CMAKE_COMMAND ${ENV_CMAKE_COMMAND} PARENT_SCOPE)
set(ENV_CMAKE_SILENT_COMMAND ${ENV_CMAKE_SILENT_COMMAND} PARENT_SCOPE)