set(BUILDMASTER_TOOLS_CMAKE_SRCDIR "${BUILDMASTER_TOOLS_CMAKE_SRCDIR}" PARENT_SCOPE)
set(BUILDMASTER_SCRIPTS_CMAKEDIR "${BUILDMASTER_SCRIPTS_CMAKEDIR}" PARENT_SCOPE)
set(ENV_CMAKE_COMMAND ${ENV_CMAKE_COMMAND} PARENT_SCOPE)
set(ENV_CMAKE_SILENT_COMMAND ${ENV_CMAKE_SILENT_COMMAND} PARENT_SCOPE)