file(APPEND "${BUILDMASTER_TOOLCHAIN_FILE}"
	"set(BUILDMASTER_TOOLS_CMAKE_SRCDIR \"${BUILDMASTER_TOOLS_CMAKE_SRCDIR}\")\n"
	"set(BUILDMASTER_SCRIPTS_CMAKEDIR \"${BUILDMASTER_SCRIPTS_CMAKEDIR}\")\n"
	"set(ENV_CMAKE_COMMAND ${ENV_CMAKE_COMMAND})\n"
	"set(ENV_CMAKE_SILENT_COMMAND ${ENV_CMAKE_SILENT_COMMAND})\n"
)