if(NOT BUILDMASTER_CONFIGURED)
	set(BUILDMASTER_TOOLS_FILE_SRCDIR "${CMAKE_CURRENT_LIST_DIR}")
	set(BUILDMASTER_SCRIPTS_FILE_DIR "${BUILDMASTER_SCRIPTSDIR}/file")
	file(MAKE_DIRECTORY "${BUILDMASTER_SCRIPTS_FILE_DIR}")

	include("${CMAKE_CURRENT_LIST_DIR}/update_toolchain.cmake")
endif()