if(NOT BUILDMASTER_TOOLS_FILE_SRCDIR)
	set(BUILDMASTER_TOOLS_FILE_SRCDIR "${CMAKE_CURRENT_LIST_DIR}" CACHE INTERNAL
		"tools/file source dir")
	set(BUILDMASTER_SCRIPTS_FILE_DIR "${BUILDMASTER_SCRIPTSDIR}/file" CACHE INTERNAL
		"Generated file-tool scripts")
	file(MAKE_DIRECTORY "${BUILDMASTER_SCRIPTS_FILE_DIR}")
	include("${CMAKE_CURRENT_LIST_DIR}/update_toolchain.cmake")
endif()
