set(BUILDMASTER_TOOLS_MESON_SRC_DIR "${CMAKE_CURRENT_LIST_DIR}")
set(BUILDMASTER_SCRIPTS_MESON_DIR "${BUILDMASTER_SCRIPTS_DIR}/meson")
find_program(MESON_EXECUTABLE meson QUIET)
if(NOT MESON_EXECUTABLE)
	message(FATAL_ERROR "Meson executable not found: please install Meson or ensure it's on PATH.")
endif()
get_filename_component(MESON_EXECUTABLE "${MESON_EXECUTABLE}" NAME)
set(_env_meson_list ${ENV_RUNNER} ${MESON_EXECUTABLE})
set(_env_meson_list_silent ${ENV_RUNNER_SILENT} ${MESON_EXECUTABLE})
prepare_command(ENV_MESON_COMMAND "${_env_meson_list}")
prepare_command(ENV_MESON_SILENT_COMMAND "${_env_meson_list_silent}")