set(BUILDMASTER_TOOLS_MESON_SRCDIR "${BUILDMASTER_TOOLS_MESON_SRCDIR}" PARENT_SCOPE)
set(BUILDMASTER_SCRIPTS_MESON_DIR "${BUILDMASTER_SCRIPTS_MESON_DIR}" PARENT_SCOPE)
set(ENV_MESON_COMMAND ${ENV_MESON_COMMAND} PARENT_SCOPE)
set(ENV_MESON_SILENT_COMMAND ${ENV_MESON_SILENT_COMMAND} PARENT_SCOPE)