file(APPEND "${BUILDMASTER_TOOLCHAIN_FILE}"
	"set(BUILDMASTER_TOOLS_MESON_SRCDIR \"${BUILDMASTER_TOOLS_MESON_SRCDIR}\")\n"
	"set(BUILDMASTER_SCRIPTS_MESON_DIR \"${BUILDMASTER_SCRIPTS_MESON_DIR}\")\n"
	"set(ENV_MESON_COMMAND ${ENV_MESON_COMMAND})\n"
	"set(ENV_MESON_SILENT_COMMAND ${ENV_MESON_SILENT_COMMAND})\n"
)
