buildmaster_toolchain_export(BUILDMASTER_TOOLS_MESON_SRCDIR "${BUILDMASTER_TOOLS_MESON_SRCDIR}")
buildmaster_toolchain_export(BUILDMASTER_SCRIPTS_MESON_DIR "${BUILDMASTER_SCRIPTS_MESON_DIR}")
buildmaster_toolchain_export_raw("set(ENV_MESON_COMMAND ${ENV_MESON_COMMAND})")
buildmaster_toolchain_export_raw("set(ENV_MESON_SILENT_COMMAND ${ENV_MESON_SILENT_COMMAND})")
buildmaster_toolchain_export_raw("set(ENV_MESON_COMPILE_COMMAND ${ENV_MESON_COMPILE_COMMAND})")