# =============================================================================
# tools/git/helpers.cmake
# =============================================================================
# API:
#   create_git_reset_file(<out> <component_id> <title> <repo_dir>)
#   create_git_patch_file(<out> <component_id> <title> <repo_dir> <patches>)
#   create_git_fetch(<out> <component_id> <title> <repo_dir>)
#   create_git_switch_branch(<out> <component_id> <title> <repo_dir> <branch>)
#
# Git runs ONLY at parent configure time via:
#   include(${out})
#
# component_id ties the repo to post-install reset and buildmaster_clean.
# buildmaster_clean: reset --hard + clean -fd, then delete
# BUILDMASTER_GIT_CONFIGURE_STAMP so the next cmake --build re-runs parent
# configure (CMAKE_CONFIGURE_DEPENDS) and re-executes include(git) scripts.
# =============================================================================

function(_buildmaster_ensure_clean_target)
	if(NOT TARGET buildmaster_clean)
		add_custom_target(buildmaster_clean
			COMMENT "BuildMaster: resetting registered git repos and invalidating parent configure"
		)
	endif()
endfunction()

function(_buildmaster_git_toplevel _out _path)
	get_filename_component(_abs "${_path}" ABSOLUTE)
	if(NOT GIT_EXECUTABLE)
		set(${_out} "${_abs}" PARENT_SCOPE)
		return()
	endif()
	execute_process(
		COMMAND ${GIT_EXECUTABLE} -C "${_abs}" rev-parse --show-toplevel
		OUTPUT_VARIABLE _root
		OUTPUT_STRIP_TRAILING_WHITESPACE
		ERROR_QUIET
		RESULT_VARIABLE _rc
	)
	if(_rc EQUAL 0 AND NOT _root STREQUAL "")
		set(${_out} "${_root}" PARENT_SCOPE)
	else()
		set(${_out} "${_abs}" PARENT_SCOPE)
	endif()
endfunction()

function(_buildmaster_git_marker_path _out _git_root)
	string(SHA1 _hash "${_git_root}")
	set(${_out} "${BUILDMASTER_SCRIPTS_GIT_DIR}/post_install_reset_${_hash}.cmake" PARENT_SCOPE)
endfunction()

function(_buildmaster_register_post_install_reset _git_root)
	_buildmaster_git_marker_path(_marker "${_git_root}")
	set(_git_cmd_line "")
	foreach(_tok IN LISTS ENV_GIT_SILENT_COMMAND)
		string(APPEND _git_cmd_line " \"${_tok}\"")
	endforeach()
	file(WRITE "${_marker}"
"# Auto-generated by BuildMaster – post-install git reset (one repo)
execute_process(
	COMMAND${_git_cmd_line} -C \"${_git_root}\" reset --hard
	RESULT_VARIABLE _rc
)
if(NOT _rc EQUAL 0)
	message(WARNING \"BuildMaster: git reset --hard failed in ${_git_root} (exit \${_rc})\")
endif()
execute_process(
	COMMAND${_git_cmd_line} -C \"${_git_root}\" clean -fd
	RESULT_VARIABLE _rc
)
if(NOT _rc EQUAL 0)
	message(WARNING \"BuildMaster: git clean -fd failed in ${_git_root} (exit \${_rc})\")
endif()
")
endfunction()

function(_buildmaster_git_register_op _component_id _git_repo_dir)
	sanitize_for_filename(_cid "${_component_id}")
	_buildmaster_git_toplevel(_git_root "${_git_repo_dir}")
	_buildmaster_register_post_install_reset("${_git_root}")
	set_property(GLOBAL PROPERTY BUILDMASTER_GIT_ROOT_${_cid} "${_git_root}")

	if(BUILDMASTER_CLEAN_RESET_REPOS)
		_buildmaster_ensure_clean_target()
		set(_clean_target "buildmaster_clean_git_${_cid}")
		if(NOT TARGET ${_clean_target})
			if(NOT DEFINED BUILDMASTER_GIT_CONFIGURE_STAMP OR BUILDMASTER_GIT_CONFIGURE_STAMP STREQUAL "")
				set(_stamp "${BUILDMASTER_SCRIPTSDIR}/git_configure.stamp")
			else()
				set(_stamp "${BUILDMASTER_GIT_CONFIGURE_STAMP}")
			endif()
			add_custom_target(${_clean_target}
				COMMAND ${CMAKE_COMMAND} -E echo "BuildMaster: resetting git repo ${_git_root} (${_cid})"
				COMMAND ${ENV_GIT_SILENT_COMMAND} -C "${_git_root}" reset --hard
				COMMAND ${ENV_GIT_SILENT_COMMAND} -C "${_git_root}" clean -fd
				COMMAND ${CMAKE_COMMAND} -E echo "BuildMaster: invalidating parent configure (remove git stamp)"
				COMMAND ${CMAKE_COMMAND} -E rm -f "${_stamp}"
				COMMENT "Resetting git repo ${_cid} and invalidating parent configure"
				VERBATIM
			)
			add_dependencies(buildmaster_clean ${_clean_target})
		endif()
	endif()
endfunction()

function(buildmaster_git_post_install_marker_for_srcdir _out _srcdir)
	_buildmaster_git_toplevel(_git_root "${_srcdir}")
	_buildmaster_git_marker_path(_marker "${_git_root}")
	if(EXISTS "${_marker}")
		set(${_out} "${_marker}" PARENT_SCOPE)
	else()
		set(${_out} "" PARENT_SCOPE)
	endif()
endfunction()


function(create_git_patch_file _file _component_id _title _git_repo_dir _git_paches)
	set(GIT_REPO "${_git_repo_dir}")
	list_join(GIT_PATCHES "${_git_paches}" " ")
	sanitize_for_filename(_safe "${_component_id}_${_title}")
	set(_GIT_PATCH_FILE "${BUILDMASTER_SCRIPTS_GIT_DIR}/git_patch_${_safe}.cmake")
	configure_file(
		"${BUILDMASTER_TOOLS_GIT_SRCDIR}/patch.cmake.in"
		"${_GIT_PATCH_FILE}"
		@ONLY
	)
	set(${_file} "${_GIT_PATCH_FILE}" PARENT_SCOPE)
	_buildmaster_git_register_op("${_component_id}" "${_git_repo_dir}")
endfunction()


function(create_git_reset_file _file _component_id _title _git_repo_dir)
	set(GIT_REPO "${_git_repo_dir}")
	sanitize_for_filename(_safe "${_component_id}_${_title}")
	set(_GIT_RESET_FILE "${BUILDMASTER_SCRIPTS_GIT_DIR}/git_reset_${_safe}.cmake")
	configure_file(
		"${BUILDMASTER_TOOLS_GIT_SRCDIR}/reset.cmake.in"
		"${_GIT_RESET_FILE}"
		@ONLY
	)
	set(${_file} "${_GIT_RESET_FILE}" PARENT_SCOPE)
	_buildmaster_git_register_op("${_component_id}" "${_git_repo_dir}")
endfunction()


function(create_git_switch_branch _file _component_id _title _git_repo_dir _git_branch)
	set(GIT_REPO "${_git_repo_dir}")
	set(GIT_BRANCH "${_git_branch}")
	sanitize_for_filename(_safe "${_component_id}_${_title}")
	set(_GIT_SWITCH_FILE "${BUILDMASTER_SCRIPTS_GIT_DIR}/git_switch_${_safe}.cmake")
	configure_file(
		"${BUILDMASTER_TOOLS_GIT_SRCDIR}/switch.cmake.in"
		"${_GIT_SWITCH_FILE}"
		@ONLY
	)
	set(${_file} "${_GIT_SWITCH_FILE}" PARENT_SCOPE)
	_buildmaster_git_register_op("${_component_id}" "${_git_repo_dir}")
endfunction()


function(create_git_fetch _file _component_id _title _git_repo_dir)
	set(GIT_REPO "${_git_repo_dir}")
	sanitize_for_filename(_safe "${_component_id}_${_title}")
	set(_GIT_FETCH_FILE "${BUILDMASTER_SCRIPTS_GIT_DIR}/git_fetch_${_safe}.cmake")
	configure_file(
		"${BUILDMASTER_TOOLS_GIT_SRCDIR}/fetch.cmake.in"
		"${_GIT_FETCH_FILE}"
		@ONLY
	)
	set(${_file} "${_GIT_FETCH_FILE}" PARENT_SCOPE)
	_buildmaster_git_register_op("${_component_id}" "${_git_repo_dir}")
endfunction()
