# =============================================================================
# tools/git/helpers.cmake
# =============================================================================
# API (breaking vs older prototypes):
#   create_git_reset_file(<out> <component_id> <title> <repo_dir>)
#   create_git_patch_file(<out> <component_id> <title> <repo_dir> <patches>)
#   create_git_fetch(<out> <component_id> <title> <repo_dir>)
#   create_git_switch_branch(<out> <component_id> <title> <repo_dir> <branch>)
#
# <component_id> must match create_cmake/meson_component's component name (e.g. vpx).
# =============================================================================

function(_buildmaster_ensure_clean_target)
	if(NOT TARGET buildmaster_clean)
		add_custom_target(buildmaster_clean
			COMMENT "BuildMaster: resetting registered git repositories and invalidating their configure"
		)
	endif()
endfunction()

function(_buildmaster_git_toplevel _out _path)
	get_filename_component(_abs "${_path}" ABSOLUTE)
	if(NOT GIT_EXECUTABLE)
		set(${_out} "${_abs}" PARENT_SCOPE)
		return()
	endif()
	execute_process(
		COMMAND ${GIT_EXECUTABLE} -C "${_abs}" rev-parse --show-toplevel
		OUTPUT_VARIABLE _root
		OUTPUT_STRIP_TRAILING_WHITESPACE
		ERROR_QUIET
		RESULT_VARIABLE _rc
	)
	if(_rc EQUAL 0 AND NOT _root STREQUAL "")
		set(${_out} "${_root}" PARENT_SCOPE)
	else()
		set(${_out} "${_abs}" PARENT_SCOPE)
	endif()
endfunction()

function(_buildmaster_git_marker_path _out _git_root)
	string(SHA1 _hash "${_git_root}")
	set(${_out} "${BUILDMASTER_SCRIPTS_GIT_DIR}/post_install_reset_${_hash}.cmake" PARENT_SCOPE)
endfunction()

function(_buildmaster_register_post_install_reset _git_root)
	_buildmaster_git_marker_path(_marker "${_git_root}")
	set(_git_cmd_line "")
	foreach(_tok IN LISTS ENV_GIT_SILENT_COMMAND)
		string(APPEND _git_cmd_line " \"${_tok}\"")
	endforeach()
	file(WRITE "${_marker}"
"# Auto-generated by BuildMaster – post-install git reset (one repo)
execute_process(
	COMMAND${_git_cmd_line} -C \"${_git_root}\" reset --hard
	RESULT_VARIABLE _rc
)
if(NOT _rc EQUAL 0)
	message(WARNING \"BuildMaster: git reset --hard failed in ${_git_root} (exit \${_rc})\")
endif()
execute_process(
	COMMAND${_git_cmd_line} -C \"${_git_root}\" clean -fd
	RESULT_VARIABLE _rc
)
if(NOT _rc EQUAL 0)
	message(WARNING \"BuildMaster: git clean -fd failed in ${_git_root} (exit \${_rc})\")
endif()
")
endfunction()

## Register a git script for a component (order preserved)
function(_buildmaster_git_register_op _component_id _script_path _git_repo_dir)
	sanitize_for_filename(_cid "${_component_id}")
	_buildmaster_git_toplevel(_git_root "${_git_repo_dir}")
	_buildmaster_register_post_install_reset("${_git_root}")

	get_property(_scripts GLOBAL PROPERTY BUILDMASTER_GIT_SCRIPTS_${_cid})
	if(NOT _scripts)
		set(_scripts "")
	endif()
	list(APPEND _scripts "${_script_path}")
	list(REMOVE_DUPLICATES _scripts)
	set_property(GLOBAL PROPERTY BUILDMASTER_GIT_SCRIPTS_${_cid} "${_scripts}")
	set_property(GLOBAL PROPERTY BUILDMASTER_GIT_ROOT_${_cid} "${_git_root}")

	# Aggregate clean: reset repo + invalidate configure of this component
	if(BUILDMASTER_CLEAN_RESET_REPOS)
		_buildmaster_ensure_clean_target()
		set(_clean_target "buildmaster_clean_git_${_cid}")
		if(NOT TARGET ${_clean_target})
			# Build-dir invalidation paths filled later by buildmaster_git_bind_component()
			set(_inv_script "${BUILDMASTER_SCRIPTS_GIT_DIR}/invalidate_${_cid}.cmake")
			file(WRITE "${_inv_script}"
"# Placeholder – rewritten when create_*_stages binds the component build dir
message(STATUS \"BuildMaster: no build-dir bound yet for component ${_cid}\")
")
			add_custom_target(${_clean_target}
				COMMAND ${CMAKE_COMMAND} -E echo "BuildMaster: resetting git repo ${_git_root} (${_cid})"
				COMMAND ${ENV_GIT_SILENT_COMMAND} -C "${_git_root}" reset --hard
				COMMAND ${ENV_GIT_SILENT_COMMAND} -C "${_git_root}" clean -fd
				COMMAND ${CMAKE_COMMAND} -P "${_inv_script}"
				COMMENT "Resetting git + invalidating configure for ${_cid}"
				VERBATIM
			)
			add_dependencies(buildmaster_clean ${_clean_target})
		endif()
	endif()
endfunction()

## Called from create_*_stages: bind builddir + system so clean can invalidate configure
function(buildmaster_git_bind_component _component_id _builddir _build_system)
	sanitize_for_filename(_cid "${_component_id}")
	get_property(_root GLOBAL PROPERTY BUILDMASTER_GIT_ROOT_${_cid})
	if(NOT _root)
		return() # no git ops for this component
	endif()
	set_property(GLOBAL PROPERTY BUILDMASTER_GIT_BUILDDIR_${_cid} "${_builddir}")
	set_property(GLOBAL PROPERTY BUILDMASTER_GIT_SYSTEM_${_cid} "${_build_system}")

	set(_inv_script "${BUILDMASTER_SCRIPTS_GIT_DIR}/invalidate_${_cid}.cmake")
	if(_build_system STREQUAL "meson")
		file(WRITE "${_inv_script}"
"# Auto-generated: invalidate Meson configure for ${_cid}
set(_bd \"${_builddir}\")
if(EXISTS \"\${_bd}/build.ninja\")
	file(REMOVE \"\${_bd}/build.ninja\")
	message(STATUS \"BuildMaster: removed \${_bd}/build.ninja (force reconfigure ${_cid})\")
endif()
# Also drop meson private stamp if present
if(EXISTS \"\${_bd}/meson-private\")
	file(REMOVE_RECURSE \"\${_bd}/meson-private\")
endif()
")
	else()
		file(WRITE "${_inv_script}"
"# Auto-generated: invalidate CMake configure for ${_cid}
set(_bd \"${_builddir}\")
if(EXISTS \"\${_bd}/CMakeCache.txt\")
	file(REMOVE \"\${_bd}/CMakeCache.txt\")
	message(STATUS \"BuildMaster: removed \${_bd}/CMakeCache.txt (force reconfigure ${_cid})\")
endif()
if(EXISTS \"\${_bd}/build.ninja\")
	file(REMOVE \"\${_bd}/build.ninja\")
endif()
")
	endif()
endfunction()

## Path of post-install marker for a srcdir (empty if none)
function(buildmaster_git_post_install_marker_for_srcdir _out _srcdir)
	_buildmaster_git_toplevel(_git_root "${_srcdir}")
	_buildmaster_git_marker_path(_marker "${_git_root}")
	if(EXISTS "${_marker}")
		set(${_out} "${_marker}" PARENT_SCOPE)
	else()
		set(${_out} "" PARENT_SCOPE)
	endif()
endfunction()

## Semicolon-separated list of git scripts for component (may be empty)
function(buildmaster_git_scripts_for_component _out _component_id)
	sanitize_for_filename(_cid "${_component_id}")
	get_property(_scripts GLOBAL PROPERTY BUILDMASTER_GIT_SCRIPTS_${_cid})
	if(_scripts)
		set(${_out} "${_scripts}" PARENT_SCOPE)
	else()
		set(${_out} "" PARENT_SCOPE)
	endif()
endfunction()


function(create_git_patch_file _file _component_id _title _git_repo_dir _git_paches)
	set(GIT_REPO "${_git_repo_dir}")
	list_join(GIT_PATCHES "${_git_paches}" " ")
	sanitize_for_filename(_safe "${_component_id}_${_title}")
	set(_GIT_PATCH_FILE "${BUILDMASTER_SCRIPTS_GIT_DIR}/git_patch_${_safe}.cmake")
	configure_file(
		"${BUILDMASTER_TOOLS_GIT_SRCDIR}/patch.cmake.in"
		"${_GIT_PATCH_FILE}"
		@ONLY
	)
	set(${_file} "${_GIT_PATCH_FILE}" PARENT_SCOPE)
	_buildmaster_git_register_op("${_component_id}" "${_GIT_PATCH_FILE}" "${_git_repo_dir}")
endfunction()


function(create_git_reset_file _file _component_id _title _git_repo_dir)
	set(GIT_REPO "${_git_repo_dir}")
	sanitize_for_filename(_safe "${_component_id}_${_title}")
	set(_GIT_RESET_FILE "${BUILDMASTER_SCRIPTS_GIT_DIR}/git_reset_${_safe}.cmake")
	configure_file(
		"${BUILDMASTER_TOOLS_GIT_SRCDIR}/reset.cmake.in"
		"${_GIT_RESET_FILE}"
		@ONLY
	)
	set(${_file} "${_GIT_RESET_FILE}" PARENT_SCOPE)
	_buildmaster_git_register_op("${_component_id}" "${_GIT_RESET_FILE}" "${_git_repo_dir}")
endfunction()


function(create_git_switch_branch _file _component_id _title _git_repo_dir _git_branch)
	set(GIT_REPO "${_git_repo_dir}")
	set(GIT_BRANCH "${_git_branch}")
	sanitize_for_filename(_safe "${_component_id}_${_title}")
	set(_GIT_SWITCH_FILE "${BUILDMASTER_SCRIPTS_GIT_DIR}/git_switch_${_safe}.cmake")
	configure_file(
		"${BUILDMASTER_TOOLS_GIT_SRCDIR}/switch.cmake.in"
		"${_GIT_SWITCH_FILE}"
		@ONLY
	)
	set(${_file} "${_GIT_SWITCH_FILE}" PARENT_SCOPE)
	_buildmaster_git_register_op("${_component_id}" "${_GIT_SWITCH_FILE}" "${_git_repo_dir}")
endfunction()


function(create_git_fetch _file _component_id _title _git_repo_dir)
	set(GIT_REPO "${_git_repo_dir}")
	sanitize_for_filename(_safe "${_component_id}_${_title}")
	set(_GIT_FETCH_FILE "${BUILDMASTER_SCRIPTS_GIT_DIR}/git_fetch_${_safe}.cmake")
	configure_file(
		"${BUILDMASTER_TOOLS_GIT_SRCDIR}/fetch.cmake.in"
		"${_GIT_FETCH_FILE}"
		@ONLY
	)
	set(${_file} "${_GIT_FETCH_FILE}" PARENT_SCOPE)
	_buildmaster_git_register_op("${_component_id}" "${_GIT_FETCH_FILE}" "${_git_repo_dir}")
endfunction()
