# =============================================================================
# tools/git/helpers.cmake
# =============================================================================
# Declarative git ops bound to a component id.
# Each create_git_* generates a script and include()s it immediately at parent
# configure (no out-var). component_id ties the repo to post-install reset and
# buildmaster_clean.
# =============================================================================

include("${CMAKE_CURRENT_LIST_DIR}/../../log.cmake")

## @brief Ensure the aggregate buildmaster_clean target exists.
function(_buildmaster_ensure_clean_target)
	buildmaster_message(GIT LOWLEVEL "Entering _buildmaster_ensure_clean_target")
	if(NOT TARGET buildmaster_clean)
		add_custom_target(buildmaster_clean
			COMMENT "BuildMaster: resetting registered git repos and invalidating parent configure"
		)
	endif()
	buildmaster_message(GIT LOWLEVEL "Exiting _buildmaster_ensure_clean_target")
endfunction()

## @brief Resolve the git toplevel for a path (or the path itself).
## @param[out] _out  Parent-scope absolute toplevel or path.
## @param[in]  _path Repository path or worktree path.
function(_buildmaster_git_toplevel _out _path)
	buildmaster_message(GIT LOWLEVEL "Entering _buildmaster_git_toplevel")
	get_filename_component(_abs "${_path}" ABSOLUTE)
	if(NOT GIT_EXECUTABLE)
		set(${_out} "${_abs}" PARENT_SCOPE)
		buildmaster_message(GIT LOWLEVEL "Exiting _buildmaster_git_toplevel")
		return()
	endif()
	execute_process(
		COMMAND ${GIT_EXECUTABLE} -C "${_abs}" rev-parse --show-toplevel
		OUTPUT_VARIABLE _root
		OUTPUT_STRIP_TRAILING_WHITESPACE
		ERROR_QUIET
		RESULT_VARIABLE _rc
	)
	if(_rc EQUAL 0 AND NOT _root STREQUAL "")
		set(${_out} "${_root}" PARENT_SCOPE)
	else()
		set(${_out} "${_abs}" PARENT_SCOPE)
	endif()
	buildmaster_message(GIT LOWLEVEL "Exiting _buildmaster_git_toplevel")
endfunction()

## @brief Path of the post-install reset script for a git root.
## @param[out] _out       Parent-scope marker path.
## @param[in]  _git_root  Absolute git toplevel.
function(_buildmaster_git_marker_path _out _git_root)
	buildmaster_message(GIT LOWLEVEL "Entering _buildmaster_git_marker_path")
	string(SHA1 _hash "${_git_root}")
	set(${_out} "${BUILDMASTER_SCRIPTS_GIT_DIR}/post_install_reset_${_hash}.cmake"
		PARENT_SCOPE)
	buildmaster_message(GIT LOWLEVEL "Exiting _buildmaster_git_marker_path")
endfunction()

## @brief Write the post-install reset -P script for one git root.
## @param[in] _git_root Absolute git toplevel.
function(_buildmaster_register_post_install_reset _git_root)
	_buildmaster_git_marker_path(_marker "${_git_root}")
	set(_git_cmd_line "")
	foreach(_tok IN LISTS ENV_GIT_SILENT_COMMAND)
		string(APPEND _git_cmd_line " \"${_tok}\"")
	endforeach()
	file(WRITE "${_marker}"
"# Auto-generated by BuildMaster – post-install git reset (one repo)
include(\"${BUILDMASTER_SRCDIR}/log.cmake\")
if(COMMAND buildmaster_loglevel_init)
	buildmaster_loglevel_init()
endif()
execute_process(
	COMMAND${_git_cmd_line} -C \"${_git_root}\" reset --hard
	RESULT_VARIABLE _rc
)
if(NOT _rc EQUAL 0)
	buildmaster_message(GIT WARNING \"git reset --hard failed in ${_git_root} (exit \${_rc})\")
endif()
execute_process(
	COMMAND${_git_cmd_line} -C \"${_git_root}\" clean -fd
	RESULT_VARIABLE _rc
)
if(NOT _rc EQUAL 0)
	buildmaster_message(GIT WARNING \"git clean -fd failed in ${_git_root} (exit \${_rc})\")
endif()
")
endfunction()


## @brief Register a component id with a git root for clean / post-install.
## @param[in] _component_id Component identifier (filesystem-sanitized key).
## @param[in] _git_repo_dir Repository or worktree path.
function(_buildmaster_git_register_op _component_id _git_repo_dir)
	buildmaster_message(GIT LOWLEVEL "Entering _buildmaster_git_register_op")
	sanitize_for_filename(_cid "${_component_id}")
	_buildmaster_git_toplevel(_git_root "${_git_repo_dir}")
	_buildmaster_register_post_install_reset("${_git_root}")
	set_property(GLOBAL PROPERTY BUILDMASTER_GIT_ROOT_${_cid} "${_git_root}")

	if(BUILDMASTER_CLEAN_RESET_REPOS)
		_buildmaster_ensure_clean_target()
		set(_clean_target "buildmaster_clean_git_${_cid}")
		if(NOT TARGET ${_clean_target})
			if(NOT DEFINED BUILDMASTER_GIT_CONFIGURE_STAMP
					OR BUILDMASTER_GIT_CONFIGURE_STAMP STREQUAL "")
				set(_stamp "${BUILDMASTER_SCRIPTSDIR}/git_configure.stamp")
			else()
				set(_stamp "${BUILDMASTER_GIT_CONFIGURE_STAMP}")
			endif()
			add_custom_target(${_clean_target}
				COMMAND ${CMAKE_COMMAND} -E echo
					"BuildMaster: resetting git repo ${_git_root} (${_cid})"
				COMMAND ${ENV_GIT_SILENT_COMMAND} -C "${_git_root}" reset --hard
				COMMAND ${ENV_GIT_SILENT_COMMAND} -C "${_git_root}" clean -fd
				COMMAND ${CMAKE_COMMAND} -E echo
					"BuildMaster: invalidating parent configure (remove git stamp)"
				COMMAND ${CMAKE_COMMAND} -E rm -f "${_stamp}"
				COMMENT "Resetting git repo ${_cid} and invalidating parent configure"
				VERBATIM
			)
			add_dependencies(buildmaster_clean ${_clean_target})
		endif()
	endif()
	buildmaster_message(GIT LOWLEVEL "Exiting _buildmaster_git_register_op")
endfunction()

## @brief Resolve post-install reset script path for a source directory.
## @param[out] _out     Parent-scope path, or empty if none registered.
## @param[in]  _srcdir  Component source directory (any path inside the repo).
function(buildmaster_git_post_install_marker_for_srcdir _out _srcdir)
	buildmaster_message(GIT LOWLEVEL "Entering buildmaster_git_post_install_marker_for_srcdir")
	_buildmaster_git_toplevel(_git_root "${_srcdir}")
	_buildmaster_git_marker_path(_marker "${_git_root}")
	if(EXISTS "${_marker}")
		set(${_out} "${_marker}" PARENT_SCOPE)
	else()
		set(${_out} "" PARENT_SCOPE)
	endif()
	buildmaster_message(GIT LOWLEVEL "Exiting buildmaster_git_post_install_marker_for_srcdir")
endfunction()

## @brief Apply git patches at parent configure; register post-install reset.
## @param[in] _component_id Component identifier (ties to install reset / clean).
## @param[in] _title        Human-readable title (script filename).
## @param[in] _git_repo_dir Repository working tree.
## @param[in] _git_patches  List of patch files (joined for the apply command).
## @note Generates the script and include()s it immediately. No out-variable.
function(create_git_patch_file _component_id _title _git_repo_dir _git_patches)
	buildmaster_message(GIT LOWLEVEL "Entering create_git_patch_file")
	set(GIT_REPO "${_git_repo_dir}")
	list_join(GIT_PATCHES "${_git_patches}" " ")
	sanitize_for_filename(_safe "${_component_id}_${_title}")
	set(_GIT_PATCH_FILE "${BUILDMASTER_SCRIPTS_GIT_DIR}/git_patch_${_safe}.cmake")
	configure_file(
		"${BUILDMASTER_TOOLS_GIT_SRCDIR}/patch.cmake.in"
		"${_GIT_PATCH_FILE}"
		@ONLY
	)
	include("${_GIT_PATCH_FILE}")
	_buildmaster_git_register_op("${_component_id}" "${_git_repo_dir}")
	buildmaster_message(GIT DEBUG "Applied git patch for ${_component_id}")
	buildmaster_message(GIT LOWLEVEL "Exiting create_git_patch_file")
endfunction()

## @brief git reset --hard + clean -fd at parent configure; register post-install.
## @param[in] _component_id Component identifier.
## @param[in] _title        Human-readable title (script filename).
## @param[in] _git_repo_dir Repository working tree.
## @note Generates the script and include()s it immediately. No out-variable.
function(create_git_reset_file _component_id _title _git_repo_dir)
	buildmaster_message(GIT LOWLEVEL "Entering create_git_reset_file")
	set(GIT_REPO "${_git_repo_dir}")
	sanitize_for_filename(_safe "${_component_id}_${_title}")
	set(_GIT_RESET_FILE "${BUILDMASTER_SCRIPTS_GIT_DIR}/git_reset_${_safe}.cmake")
	configure_file(
		"${BUILDMASTER_TOOLS_GIT_SRCDIR}/reset.cmake.in"
		"${_GIT_RESET_FILE}"
		@ONLY
	)
	include("${_GIT_RESET_FILE}")
	_buildmaster_git_register_op("${_component_id}" "${_git_repo_dir}")
	buildmaster_message(GIT DEBUG "Reset git repo for ${_component_id}")
	buildmaster_message(GIT LOWLEVEL "Exiting create_git_reset_file")
endfunction()

## @brief Switch branch at parent configure; register post-install reset.
## @param[in] _component_id Component identifier.
## @param[in] _title        Human-readable title (script filename).
## @param[in] _git_repo_dir Repository working tree.
## @param[in] _git_branch   Branch name.
## @note Generates the script and include()s it immediately. No out-variable.
function(create_git_switch_branch _component_id _title _git_repo_dir _git_branch)
	buildmaster_message(GIT LOWLEVEL "Entering create_git_switch_branch")
	set(GIT_REPO "${_git_repo_dir}")
	set(GIT_BRANCH "${_git_branch}")
	sanitize_for_filename(_safe "${_component_id}_${_title}")
	set(_GIT_SWITCH_FILE "${BUILDMASTER_SCRIPTS_GIT_DIR}/git_switch_${_safe}.cmake")
	configure_file(
		"${BUILDMASTER_TOOLS_GIT_SRCDIR}/switch.cmake.in"
		"${_GIT_SWITCH_FILE}"
		@ONLY
	)
	include("${_GIT_SWITCH_FILE}")
	_buildmaster_git_register_op("${_component_id}" "${_git_repo_dir}")
	buildmaster_message(GIT DEBUG "Switched ${_component_id} to ${_git_branch}")
	buildmaster_message(GIT LOWLEVEL "Exiting create_git_switch_branch")
endfunction()

## @brief git fetch at parent configure; register post-install reset.
## @param[in] _component_id Component identifier.
## @param[in] _title        Human-readable title (script filename).
## @param[in] _git_repo_dir Repository working tree.
## @note Generates the script and include()s it immediately. No out-variable.
function(create_git_fetch _component_id _title _git_repo_dir)
	buildmaster_message(GIT LOWLEVEL "Entering create_git_fetch")
	set(GIT_REPO "${_git_repo_dir}")
	sanitize_for_filename(_safe "${_component_id}_${_title}")
	set(_GIT_FETCH_FILE "${BUILDMASTER_SCRIPTS_GIT_DIR}/git_fetch_${_safe}.cmake")
	configure_file(
		"${BUILDMASTER_TOOLS_GIT_SRCDIR}/fetch.cmake.in"
		"${_GIT_FETCH_FILE}"
		@ONLY
	)
	include("${_GIT_FETCH_FILE}")
	_buildmaster_git_register_op("${_component_id}" "${_git_repo_dir}")
	buildmaster_message(GIT DEBUG "Fetched git for ${_component_id}")
	buildmaster_message(GIT LOWLEVEL "Exiting create_git_fetch")
endfunction()
