# =============================================================================
# tools/git/internal.cmake — clean target, toplevel, post-install reset
# =============================================================================

## @brief Ensure the aggregate `buildmaster_clean` custom target exists.
## @note Created once. Individual `buildmaster_clean_git_<id>` targets are
##       attached when BUILDMASTER_CLEAN_RESET_REPOS is on.
## @note `buildmaster_clean` is a **target**, not a public command.
function(_bm_git_ensure_clean_target)
	_bm_log_message(GIT LOWLEVEL "Entering _bm_git_ensure_clean_target")
	if(NOT TARGET buildmaster_clean)
		add_custom_target(buildmaster_clean
			COMMENT "BuildMaster: resetting registered git repos and invalidating parent configure"
		)
	endif()
	_bm_log_message(GIT LOWLEVEL "Exiting _bm_git_ensure_clean_target")
endfunction()

## @brief Resolve the git toplevel for a path (or the path itself).
## @param[out] _out  Parent-scope absolute git root or the input path.
## @param[in]  _path Directory that should live inside a git work tree.
## @note Uses `git rev-parse --show-toplevel`. If GIT_EXECUTABLE is unset or
##       the command fails, `_path` (absolutized) is returned unchanged.
function(_bm_git_toplevel _out _path)
	_bm_log_message(GIT LOWLEVEL "Entering _bm_git_toplevel")
	get_filename_component(_abs "${_path}" ABSOLUTE)
	if(NOT GIT_EXECUTABLE)
		set(${_out} "${_abs}" PARENT_SCOPE)
		_bm_log_message(GIT LOWLEVEL "Exiting _bm_git_toplevel")
		return()
	endif()
	execute_process(
		COMMAND ${GIT_EXECUTABLE} -C "${_abs}" rev-parse --show-toplevel
		OUTPUT_VARIABLE _root
		OUTPUT_STRIP_TRAILING_WHITESPACE
		ERROR_QUIET
		RESULT_VARIABLE _rc
	)
	if(_rc EQUAL 0 AND NOT _root STREQUAL "")
		file(TO_CMAKE_PATH "${_root}" _root)
		set(${_out} "${_root}" PARENT_SCOPE)
	else()
		set(${_out} "${_abs}" PARENT_SCOPE)
	endif()
	_bm_log_message(GIT LOWLEVEL "Exiting _bm_git_toplevel")
endfunction()

## @brief FATAL unless `_path` is its own git work tree and not the host repo.
## @param[in] _path Directory passed to RESET / PATCH / FETCH / SWITCH / clean.
## @note `git rev-parse --show-toplevel` must equal `_path`. A wrapper
##       directory (no `.git`) climbs to another repo — another component
##       or the host — and is refused.
## @note Toplevel equal to `CMAKE_SOURCE_DIR`'s toplevel is FATAL even if
##       the caller passed that directory on purpose.
function(_bm_git_require_component_root _path)
	_bm_log_message(GIT LOWLEVEL "Entering _bm_git_require_component_root")
	get_filename_component(_abs "${_path}" ABSOLUTE)
	file(TO_CMAKE_PATH "${_abs}" _abs)
	get_filename_component(_host "${CMAKE_SOURCE_DIR}" ABSOLUTE)
	file(TO_CMAKE_PATH "${_host}" _host)
	_bm_git_toplevel(_root "${_abs}")
	file(TO_CMAKE_PATH "${_root}" _root)
	_bm_git_toplevel(_host_root "${_host}")
	file(TO_CMAKE_PATH "${_host_root}" _host_root)
	if(_root STREQUAL "${_host_root}")
		_bm_log_message(GIT FATAL
			"Refusing git on '${_abs}': toplevel '${_root}' is the host project (CMAKE_SOURCE_DIR).")
	endif()
	if(NOT _root STREQUAL "${_abs}")
		_bm_log_message(GIT FATAL
			"Refusing git on '${_abs}': not a git work tree (toplevel '${_root}'). GIT ops run only on the component work tree, never a wrapper or a sibling.")
	endif()
	_bm_log_message(GIT LOWLEVEL "Exiting _bm_git_require_component_root")
endfunction()

## @brief Path of the post-install reset -P script for one git root.
## @param[out] _out      Parent-scope script path under BUILDMASTER_SCRIPTS_GIT_DIR.
## @param[in]  _git_root Absolute git toplevel.
## @note Filename is `post_install_reset_<sha1(root)>.cmake` so one script
##       is shared by every component that lives in the same repo.
function(_bm_git_marker_path _out _git_root)
	string(SHA1 _hash "${_git_root}")
	set(${_out} "${BUILDMASTER_SCRIPTS_GIT_DIR}/post_install_reset_${_hash}.cmake" PARENT_SCOPE)
endfunction()

## @brief Write the post-install reset -P script for one git root.
## @param[in] _git_root Absolute git toplevel.
## @note Only written when a PATCH was queued. FETCH / SWITCH / RESET-only
##       leave the tree clean after configure; install must not reset again.
## @note The generated script runs `git reset --hard` then `git clean -fd`
##       via ENV_GIT_SILENT_COMMAND. Failures are WARNING (install already
##       succeeded). Invoked from install_exec after the component install.
function(_bm_git_register_post_install_reset _git_root)
	_bm_log_message(GIT LOWLEVEL "Entering _bm_git_register_post_install_reset")
	_bm_git_require_component_root("${_git_root}")
	_bm_git_marker_path(_marker "${_git_root}")
	set(_git_cmd_line "")
	foreach(_tok IN LISTS ENV_GIT_SILENT_COMMAND)
		string(APPEND _git_cmd_line " \"${_tok}\"")
	endforeach()
	file(WRITE "${_marker}"
"# Auto-generated by BuildMaster – post-install git reset (one repo)
include(\"${BUILDMASTER_SRCDIR}/log.cmake\")
if(COMMAND _bm_log_level_init)
	_bm_log_level_init()
endif()
execute_process(
	COMMAND${_git_cmd_line} -C \"${_git_root}\" reset --hard
	RESULT_VARIABLE _rc
	OUTPUT_VARIABLE _out
	ERROR_VARIABLE _err
	OUTPUT_STRIP_TRAILING_WHITESPACE
	ERROR_STRIP_TRAILING_WHITESPACE
)
if(NOT _rc EQUAL 0)
	_bm_log_message(GIT WARNING \"git reset --hard failed in ${_git_root} (exit \${_rc})\")
elseif(NOT \"\${_out}\" STREQUAL \"\")
	_bm_log_message(GIT STATUS \"\${_out}\")
endif()
execute_process(
	COMMAND${_git_cmd_line} -C \"${_git_root}\" clean -fd
	RESULT_VARIABLE _rc
	OUTPUT_VARIABLE _out
	ERROR_VARIABLE _err
	OUTPUT_STRIP_TRAILING_WHITESPACE
	ERROR_STRIP_TRAILING_WHITESPACE
)
if(NOT _rc EQUAL 0)
	_bm_log_message(GIT WARNING \"git clean -fd failed in ${_git_root} (exit \${_rc})\")
endif()
")
	_bm_log_message(GIT DEBUG "post-install reset script ${_marker}")
	_bm_log_message(GIT LOWLEVEL "Exiting _bm_git_register_post_install_reset")
endfunction()

## @brief Register a component id with a git root for clean targets.
## @param[in] _component_id  Component id (sanitized for target names).
## @param[in] _git_repo_dir  Path inside the work tree (srcdir).
## @note Stores BUILDMASTER_GIT_ROOT_<id>. Does **not** write the
##       post-install reset marker — that is PATCH-only
##       (`_bm_tools_git_patch` → `_bm_git_register_post_install_reset`).
## @note When BUILDMASTER_CLEAN_RESET_REPOS is true, adds
##       `buildmaster_clean_git_<id>` under `buildmaster_clean`.
function(_bm_git_register_op _component_id _git_repo_dir)
	_bm_log_message(GIT LOWLEVEL "Entering _bm_git_register_op")
	_bm_git_require_component_root("${_git_repo_dir}")
	_bm_path_sanitize(_cid "${_component_id}")
	_bm_git_toplevel(_git_root "${_git_repo_dir}")
	set_property(GLOBAL PROPERTY BUILDMASTER_GIT_ROOT_${_cid} "${_git_root}")

	if(BUILDMASTER_CLEAN_RESET_REPOS)
		_bm_git_ensure_clean_target()
		set(_clean_target "buildmaster_clean_git_${_cid}")
		if(NOT TARGET ${_clean_target})
			if(NOT DEFINED BUILDMASTER_GIT_CONFIGURE_STAMP OR BUILDMASTER_GIT_CONFIGURE_STAMP STREQUAL "")
				set(_stamp "${BUILDMASTER_SCRIPTSDIR}/git_configure.stamp")
			else()
				set(_stamp "${BUILDMASTER_GIT_CONFIGURE_STAMP}")
			endif()
			add_custom_target(${_clean_target}
				COMMAND ${CMAKE_COMMAND} -E echo "BuildMaster: resetting git repo ${_git_root} (${_cid})"
				COMMAND ${ENV_GIT_SILENT_COMMAND} -C "${_git_root}" reset --hard
				COMMAND ${ENV_GIT_SILENT_COMMAND} -C "${_git_root}" clean -fd
				COMMAND ${CMAKE_COMMAND} -E echo "BuildMaster: invalidating parent configure (remove git stamp)"
				COMMAND ${CMAKE_COMMAND} -E rm -f "${_stamp}"
				COMMENT "Resetting git repo ${_cid} and invalidating parent configure"
				VERBATIM
			)
			add_dependencies(buildmaster_clean ${_clean_target})
		endif()
	endif()
	_bm_log_message(GIT DEBUG "git register ${_component_id} root=${_git_root}")
	_bm_log_message(GIT LOWLEVEL "Exiting _bm_git_register_op")
endfunction()

## @brief Resolve post-install reset script path for a source directory.
## @param[out] _out     Parent-scope path, or empty if no marker was written.
## @param[in]  _srcdir  Component source directory.
## @note Marker exists only when a PATCH was registered for that git root.
##       Used by `_bm_tools_cmake_stages` / `_bm_tools_meson_stages` so
##       install_exec can reset after install.
function(_bm_tools_git_marker _out _srcdir)
	_bm_log_message(GIT LOWLEVEL "Entering _bm_tools_git_marker")
	_bm_git_toplevel(_git_root "${_srcdir}")
	_bm_git_marker_path(_marker "${_git_root}")
	if(EXISTS "${_marker}")
		set(${_out} "${_marker}" PARENT_SCOPE)
	else()
		set(${_out} "" PARENT_SCOPE)
	endif()
	_bm_log_message(GIT LOWLEVEL "Exiting _bm_tools_git_marker")
endfunction()
