set(BUILDMASTER_TOOLS_GIT_SRC_DIR "${BUILDMASTER_TOOLS_GIT_SRC_DIR}" PARENT_SCOPE)
set(BUILDMASTER_SCRIPTS_GIT_DIR "${BUILDMASTER_SCRIPTS_GIT_DIR}" PARENT_SCOPE)
set(ENV_GIT_COMMAND ${ENV_GIT_COMMAND} PARENT_SCOPE)