file(APPEND "${BUILDMASTER_TOOLCHAIN_FILE}"
	"set(BUILDMASTER_TOOLS_GIT_SRCDIR \"${BUILDMASTER_TOOLS_GIT_SRCDIR}\")\n"
	"set(BUILDMASTER_SCRIPTS_GIT_DIR \"${BUILDMASTER_SCRIPTS_GIT_DIR}\")\n"
	"set(ENV_GIT_COMMAND ${ENV_GIT_COMMAND})\n"
	"set(ENV_GIT_SILENT_COMMAND ${ENV_GIT_SILENT_COMMAND})\n"
)