_bm_tc_export(BUILDMASTER_TOOLS_GIT_SRCDIR "${BUILDMASTER_TOOLS_GIT_SRCDIR}")
_bm_tc_export(BUILDMASTER_SCRIPTS_GIT_DIR "${BUILDMASTER_SCRIPTS_GIT_DIR}")
_bm_tc_export_raw("set(ENV_GIT_COMMAND ${ENV_GIT_COMMAND})")
_bm_tc_export_raw("set(ENV_GIT_SILENT_COMMAND ${ENV_GIT_SILENT_COMMAND})")