# =============================================================================
# component/meta/wire.cmake — INTERFACE + orphan warn
# =============================================================================

## @brief After real components exist: wire `<meta>_install` and INTERFACE.
## @note Wait edge: leaf `_install` unless the leaf is NOINSTALL, then
##       `_build` (end of that component's phase).
## @note `REPACK` metas do not INTERFACE-link static leaves (the merge
##       publishes one archive). Shared/headers leaves stay INTERFACE;
##       shared also emits WARNING (cannot fold a .so/.dll into the pack).
## @note Without REPACK, WHOLE flattens static produced files; otherwise
##       `target_link_libraries(<meta> INTERFACE <leaf>)`.
function(_bm_meta_wire)
	_bm_log_message(COMPONENT LOWLEVEL "Entering _bm_meta_wire")
	get_property(_metas GLOBAL PROPERTY BUILDMASTER_META_IDS)
	if(NOT _metas)
		_bm_log_message(COMPONENT LOWLEVEL "Exiting _bm_meta_wire")
		return()
	endif()

	foreach(_id IN LISTS _metas)
		get_property(_leaves GLOBAL PROPERTY BUILDMASTER_META_${_id}_LEAVES)
		get_property(_whole GLOBAL PROPERTY BUILDMASTER_META_${_id}_WHOLE)
		get_property(_repack GLOBAL PROPERTY BUILDMASTER_META_${_id}_REPACK)

		foreach(_leaf IN LISTS _leaves)
			_bm_graph_is_noinstall("${_leaf}" _ni)
			if(_ni)
				if(TARGET "${_leaf}_build")
					add_dependencies(${_id}_install ${_leaf}_build)
				endif()
			else()
				if(TARGET "${_leaf}_install")
					add_dependencies(${_id}_install ${_leaf}_install)
				endif()
			endif()
		endforeach()

		if(_repack)
			foreach(_leaf IN LISTS _leaves)
				get_property(_lmode GLOBAL PROPERTY BUILDMASTER_COMPONENT_${_leaf}_MODE)
				if(_lmode STREQUAL "shared")
					_bm_log_message(COMPONENT WARNING
						"meta '${_id}': REPACK cannot fold shared '${_leaf}' into one archive; the .so/.dll stays a separate INTERFACE link (the pack is not a single shared library)")
					if(TARGET "${_leaf}")
						target_link_libraries(${_id} INTERFACE ${_leaf})
					endif()
				elseif(_lmode STREQUAL "headers")
					if(TARGET "${_leaf}")
						target_link_libraries(${_id} INTERFACE ${_leaf})
					endif()
				endif()
			endforeach()
			continue()
		endif()

		if(_whole)
			set(_paths "")
			set(_emitted "")
			foreach(_leaf IN LISTS _leaves)
				get_property(_lmode GLOBAL PROPERTY BUILDMASTER_COMPONENT_${_leaf}_MODE)
				get_property(_lwhole GLOBAL PROPERTY BUILDMASTER_COMPONENT_${_leaf}_WHOLE)
				if(_lmode STREQUAL "shared" OR _lmode STREQUAL "headers")
					if(TARGET "${_leaf}")
						target_link_libraries(${_id} INTERFACE ${_leaf})
					endif()
					continue()
				endif()
				if(_lwhole)
					if(TARGET "${_leaf}")
						target_link_libraries(${_id} INTERFACE ${_leaf})
					endif()
					get_property(_files GLOBAL PROPERTY BUILDMASTER_COMPONENT_${_leaf}_FILES)
					foreach(_f IN LISTS _files)
						list(APPEND _emitted "${_f}")
					endforeach()
					continue()
				endif()
				get_property(_files GLOBAL PROPERTY BUILDMASTER_COMPONENT_${_leaf}_FILES)
				foreach(_f IN LISTS _files)
					if(_emitted)
						list(FIND _emitted "${_f}" _hit)
						if(NOT _hit EQUAL -1)
							continue()
						endif()
					endif()
					list(APPEND _emitted "${_f}")
					list(APPEND _paths "${_f}")
				endforeach()
			endforeach()
			if(_paths)
				_bm_opt_whole_items(_witems ${_paths})
				target_link_libraries(${_id} INTERFACE ${_witems})
			elseif(_whole)
				set(_any_static FALSE)
				foreach(_leaf IN LISTS _leaves)
					get_property(_lmode GLOBAL PROPERTY BUILDMASTER_COMPONENT_${_leaf}_MODE)
					if(_lmode STREQUAL "static")
						set(_any_static TRUE)
					endif()
				endforeach()
				if(NOT _any_static)
					_bm_log_message(COMPONENT INFO
						"meta '${_id}': WHOLE ignored (no static produced archives among members)")
				endif()
			endif()
		else()
			foreach(_leaf IN LISTS _leaves)
				if(TARGET "${_leaf}")
					target_link_libraries(${_id} INTERFACE ${_leaf})
				endif()
			endforeach()
		endif()
	endforeach()
	_bm_log_message(COMPONENT LOWLEVEL "Exiting _bm_meta_wire")
endfunction()

## @brief Warn once about registered components/metas with no consumer.
## @note Membership is not consumption for the meta itself, but:
##       - leaves of any meta are not orphans;
##       - a nested meta is consumed if an ancestor meta is consumed;
##       - REPACK meta members are consumed only if that meta id
##         itself is consumed; an unused repack orphans both itself and
##         inputs that nothing else consumes;
##       - host target_link_libraries to a component/meta id counts;
##       - host add_dependencies / custom-target DEPENDS on <id>,
##         <id>_install, <id>_build or <id>_configure counts (smoke,
##         BUILDONLY stages that never enter a link line).
function(_bm_meta_warn_orphans)
	_bm_log_message(COMPONENT LOWLEVEL "Entering _bm_meta_warn_orphans")
	get_property(_comps GLOBAL PROPERTY BUILDMASTER_COMPONENT_IDS)
	get_property(_metas GLOBAL PROPERTY BUILDMASTER_META_IDS)
	get_property(_dsrc GLOBAL PROPERTY BUILDMASTER_COMPONENT_DEP_SOURCES)
	get_property(_ddst GLOBAL PROPERTY BUILDMASTER_COMPONENT_DEP_DESTS)
	get_property(_lsrc GLOBAL PROPERTY BUILDMASTER_COMPONENT_LINK_SOURCES)
	get_property(_ldst GLOBAL PROPERTY BUILDMASTER_COMPONENT_LINK_DESTS)

	set(_mentioned "")
	foreach(_x IN LISTS _dsrc _ddst _lsrc _ldst)
		if(NOT "${_x}" STREQUAL "")
			list(APPEND _mentioned "${_x}")
		endif()
	endforeach()

	set(_dirs "${CMAKE_SOURCE_DIR}")
	set(_seen_dirs "${CMAKE_SOURCE_DIR}")
	while(_dirs)
		list(GET _dirs 0 _dir)
		list(REMOVE_AT _dirs 0)
		get_property(_tgts DIRECTORY "${_dir}" PROPERTY BUILDSYSTEM_TARGETS)
		foreach(_t IN LISTS _tgts)
			if(NOT TARGET "${_t}")
				continue()
			endif()
			get_property(_ll TARGET "${_t}" PROPERTY LINK_LIBRARIES)
			get_property(_il TARGET "${_t}" PROPERTY INTERFACE_LINK_LIBRARIES)
			get_property(_md TARGET "${_t}" PROPERTY MANUALLY_ADDED_DEPENDENCIES)
			foreach(_u IN LISTS _ll _il _md)
				if("${_u}" STREQUAL "")
					continue()
				endif()
				list(APPEND _mentioned "${_u}")
				foreach(_sfx IN ITEMS _install _build _configure)
					string(LENGTH "${_sfx}" _sl)
					string(LENGTH "${_u}" _ul)
					if(_ul GREATER _sl)
						math(EXPR _cut "${_ul} - ${_sl}")
						string(SUBSTRING "${_u}" ${_cut} ${_sl} _end)
						if(_end STREQUAL "${_sfx}")
							string(SUBSTRING "${_u}" 0 ${_cut} _stem)
							list(APPEND _mentioned "${_stem}")
						endif()
					endif()
				endforeach()
			endforeach()
		endforeach()
		get_property(_subs DIRECTORY "${_dir}" PROPERTY SUBDIRECTORIES)
		foreach(_s IN LISTS _subs)
			list(FIND _seen_dirs "${_s}" _hit)
			if(_hit EQUAL -1)
				list(APPEND _seen_dirs "${_s}")
				list(APPEND _dirs "${_s}")
			endif()
		endforeach()
	endwhile()

	if(_mentioned)
		list(REMOVE_DUPLICATES _mentioned)
	endif()

	get_property(_rep_ids GLOBAL PROPERTY BUILDMASTER_REPACK_IDS)
	foreach(_rid IN LISTS _rep_ids)
		set(_rep_used FALSE)
		if(_mentioned)
			list(FIND _mentioned "${_rid}" _hit)
			if(NOT _hit EQUAL -1)
				set(_rep_used TRUE)
			endif()
		endif()
		if(_rep_used)
			get_property(_rin GLOBAL PROPERTY BUILDMASTER_REPACK_${_rid}_INPUTS)
			foreach(_in IN LISTS _rin)
				if(NOT "${_in}" STREQUAL "")
					list(APPEND _mentioned "${_in}")
				endif()
			endforeach()
		endif()
	endforeach()
	if(_mentioned)
		list(REMOVE_DUPLICATES _mentioned)
	endif()

	set(_consumed_metas "")
	foreach(_m IN LISTS _metas)
		if(_mentioned)
			list(FIND _mentioned "${_m}" _hit)
			if(NOT _hit EQUAL -1)
				list(APPEND _consumed_metas "${_m}")
			endif()
		endif()
	endforeach()

	set(_changed TRUE)
	while(_changed)
		set(_changed FALSE)
		foreach(_m IN LISTS _consumed_metas)
			get_property(_members GLOBAL PROPERTY BUILDMASTER_META_${_m}_MEMBERS)
			foreach(_mem IN LISTS _members)
				_bm_meta_is("${_mem}" _mem_meta)
				if(NOT _mem_meta)
					continue()
				endif()
				list(FIND _consumed_metas "${_mem}" _hit)
				if(_hit EQUAL -1)
					list(APPEND _consumed_metas "${_mem}")
					set(_changed TRUE)
				endif()
			endforeach()
		endforeach()
	endwhile()
	if(_consumed_metas)
		list(REMOVE_DUPLICATES _consumed_metas)
	endif()

	set(_consumed_comps "")
	foreach(_c IN LISTS _comps)
		if(_mentioned)
			list(FIND _mentioned "${_c}" _hit)
			if(NOT _hit EQUAL -1)
				list(APPEND _consumed_comps "${_c}")
			endif()
		endif()
	endforeach()
	foreach(_m IN LISTS _metas)
		get_property(_leaves GLOBAL PROPERTY BUILDMASTER_META_${_m}_LEAVES)
		foreach(_l IN LISTS _leaves)
			list(APPEND _consumed_comps "${_l}")
		endforeach()
	endforeach()
	if(_consumed_comps)
		list(REMOVE_DUPLICATES _consumed_comps)
	endif()

	set(_orphans "")
	foreach(_c IN LISTS _comps)
		if(_consumed_comps)
			list(FIND _consumed_comps "${_c}" _hit)
			if(NOT _hit EQUAL -1)
				continue()
			endif()
		endif()
		list(APPEND _orphans "${_c}")
	endforeach()
	foreach(_m IN LISTS _metas)
		if(_consumed_metas)
			list(FIND _consumed_metas "${_m}" _hit)
			if(NOT _hit EQUAL -1)
				continue()
			endif()
		endif()
		list(APPEND _orphans "${_m}")
	endforeach()

	if(_orphans)
		list(REMOVE_DUPLICATES _orphans)
		string(REPLACE ";" ", " _list "${_orphans}")
		_bm_log_message(COMPONENT WARNING
			"orphan component(s) / meta(s) (not consumed by buildmaster_link / buildmaster_depend / host link / host DEPENDS / consumed REPACK meta): ${_list}")
	endif()
	_bm_log_message(COMPONENT LOWLEVEL "Exiting _bm_meta_warn_orphans")
endfunction()
