include("${CMAKE_CURRENT_LIST_DIR}/known.cmake")

get_property(_exists GLOBAL PROPERTY BUILDMASTER_PLUGINS_EXTRA_AVAILABLE DEFINED)
if(NOT _exists)
	set_property(GLOBAL PROPERTY BUILDMASTER_PLUGINS_EXTRA_AVAILABLE
		"${BUILDMASTER_TOOLS_EXTRA_KNOWN}")
endif()

get_property(_exists GLOBAL PROPERTY BUILDMASTER_PLUGINS_EXTRA_ENABLED DEFINED)
if(NOT _exists)
	set_property(GLOBAL PROPERTY BUILDMASTER_PLUGINS_EXTRA_ENABLED "")
endif()
