buildmaster_toolchain_export(BUILDMASTER_TOOLS_SRCDIR "${BUILDMASTER_TOOLS_SRCDIR}")
buildmaster_toolchain_export(BUILDMASTER_TOOLS_BINDIR "${BUILDMASTER_TOOLS_BINDIR}")
buildmaster_toolchain_export(BUILDMASTER_INSTALL_DIR "${BUILDMASTER_INSTALL_DIR}")
buildmaster_toolchain_export(BUILDMASTER_INSTALL_LIBDIR "${BUILDMASTER_INSTALL_LIBDIR}")
buildmaster_toolchain_export(BUILDMASTER_INSTALL_BINDIR "${BUILDMASTER_INSTALL_BINDIR}")
buildmaster_toolchain_export(CMAKE_BUILD_TYPE "${CMAKE_BUILD_TYPE}")
buildmaster_toolchain_export(MESON_BUILD_TYPE "${MESON_BUILD_TYPE}")