file(APPEND "${BUILDMASTER_TOOLCHAIN_FILE}"
	"set(BUILDMASTER_TOOLS_SRCDIR \"${BUILDMASTER_TOOLS_SRCDIR}\")\n"
	"set(BUILDMASTER_TOOLS_BINDIR \"${BUILDMASTER_TOOLS_BINDIR}\")\n"
	"set(BUILDMASTER_INSTALL_DIR \"${BUILDMASTER_INSTALL_DIR}\")\n"
	"set(BUILDMASTER_INSTALL_LIBDIR \"${BUILDMASTER_INSTALL_LIBDIR}\")\n"
	"set(BUILDMASTER_INSTALL_BINDIR \"${BUILDMASTER_INSTALL_BINDIR}\")\n"
	"set(CMAKE_BUILD_TYPE ${CMAKE_BUILD_TYPE})\n"
	"set(MESON_BUILD_TYPE ${MESON_BUILD_TYPE})\n"
)
