if (NOT CMAKE_BUILD_TYPE)
	set(CMAKE_BUILD_TYPE "Release" CACHE STRING "Build type" FORCE)
endif()
set(CMAKE_BUILD_TYPE ${CMAKE_BUILD_TYPE} PARENT_SCOPE)
string(TOLOWER ${CMAKE_BUILD_TYPE} MESON_BUILD_TYPE)
set(MESON_BUILD_TYPE ${MESON_BUILD_TYPE} PARENT_SCOPE)

# Optimizations
if (CMAKE_BUILD_TYPE STREQUAL "Release" AND MSVC)
	set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} /O2 /GL /Gy /arch:AVX2 /fp:fast /DNDEBUG")
	set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} /O2 /GL /Gy /arch:AVX2 /fp:fast /DNDEBUG")
	set(CMAKE_EXE_LINKER_FLAGS "${CMAKE_EXE_LINKER_FLAGS} /LTCG")
	set(CMAKE_SHARED_LINKER_FLAGS "${CMAKE_SHARED_LINKER_FLAGS} /LTCG")
endif()