set(BUILDMASTER_ENV_DIR "${BUILDMASTER_ENV_DIR}" PARENT_SCOPE)
set(BUILDMASTER_SCRIPTS_ENV_DIR "${BUILDMASTER_SCRIPTS_ENV_DIR}" PARENT_SCOPE)
set(ENV_RUNNER ${ENV_RUNNER} PARENT_SCOPE)
set(ENV_RUNNER_SILENT ${ENV_RUNNER_SILENT} PARENT_SCOPE)