buildmaster_toolchain_export(BUILDMASTER_ENV_SRCDIR "${BUILDMASTER_ENV_SRCDIR}")
buildmaster_toolchain_export(BUILDMASTER_SCRIPTS_ENVDIR "${BUILDMASTER_SCRIPTS_ENVDIR}")
buildmaster_toolchain_export_raw("set(ENV_RUNNER ${ENV_RUNNER})")
buildmaster_toolchain_export_raw("set(ENV_RUNNER_SILENT ${ENV_RUNNER_SILENT})")
buildmaster_toolchain_export_raw("set(ENV_RUNNER_COMPILE ${ENV_RUNNER_COMPILE})")
buildmaster_toolchain_export(NPROC "${NPROC}")

# Nested BUILDMASTER_CONFIGURED skips env/init_vars. Persist the prefix
# search strings so child runners and create_*_stages still see them.
if(DEFINED CFLAGS)
	buildmaster_toolchain_export(CFLAGS "${CFLAGS}")
endif()
if(DEFINED CXXFLAGS)
	buildmaster_toolchain_export(CXXFLAGS "${CXXFLAGS}")
endif()
if(DEFINED LDFLAGS)
	buildmaster_toolchain_export(LDFLAGS "${LDFLAGS}")
endif()
if(DEFINED INCLUDE)
	buildmaster_toolchain_export(INCLUDE "${INCLUDE}")
endif()
if(DEFINED LIB)
	buildmaster_toolchain_export(LIB "${LIB}")
endif()
