_bm_tc_export(BUILDMASTER_ENV_SRCDIR "${BUILDMASTER_ENV_SRCDIR}")
_bm_tc_export(BUILDMASTER_SCRIPTS_ENVDIR "${BUILDMASTER_SCRIPTS_ENVDIR}")
_bm_tc_export_raw("set(ENV_RUNNER ${ENV_RUNNER})")
_bm_tc_export_raw("set(ENV_RUNNER_SILENT ${ENV_RUNNER_SILENT})")
_bm_tc_export_raw("set(ENV_RUNNER_COMPILE ${ENV_RUNNER_COMPILE})")
_bm_tc_export(NPROC "${NPROC}")

# Nested BUILDMASTER_CONFIGURED skips env/init_vars. Persist the prefix
# search strings so child runners and create_*_stages still see them.
if(DEFINED CFLAGS)
	_bm_tc_export(CFLAGS "${CFLAGS}")
endif()
if(DEFINED CXXFLAGS)
	_bm_tc_export(CXXFLAGS "${CXXFLAGS}")
endif()
if(DEFINED LDFLAGS)
	_bm_tc_export(LDFLAGS "${LDFLAGS}")
endif()
if(DEFINED INCLUDE)
	_bm_tc_export(INCLUDE "${INCLUDE}")
endif()
if(DEFINED LIB)
	_bm_tc_export(LIB "${LIB}")
endif()
