file(APPEND "${BUILDMASTER_TOOLCHAIN_FILE}"
	"set(BUILDMASTER_ENV_SRCDIR \"${BUILDMASTER_ENV_SRCDIR}\")\n"
	"set(BUILDMASTER_SCRIPTS_ENVDIR \"${BUILDMASTER_SCRIPTS_ENVDIR}\")\n"
	"set(ENV_RUNNER ${ENV_RUNNER})\n"
	"set(ENV_RUNNER_SILENT ${ENV_RUNNER_SILENT})\n"
	"set(ENV_RUNNER_COMPILE ${ENV_RUNNER_COMPILE})\n"
	"set(NPROC \"${NPROC}\")\n"
)