set(BUILDMASTER_TOOLS_NINJA_SRC_DIR "${CMAKE_CURRENT_LIST_DIR}")
find_program(NINJA_EXECUTABLE ninja QUIET)
if(NOT NINJA_EXECUTABLE)
	message(FATAL_ERROR "Ninja executable not found: please install Ninja or ensure it's on PATH.")
endif()
get_filename_component(NINJA_EXECUTABLE "${NINJA_EXECUTABLE}" NAME)
set(_env_ninja_list ${ENV_RUNNER} ${NINJA_EXECUTABLE} "-j${NPROC}")
set(_env_ninja_silent_list ${ENV_RUNNER_SILENT} ${NINJA_EXECUTABLE} "-j${NPROC}")
prepare_command(ENV_NINJA_COMMAND "${_env_ninja_list}")
prepare_command(ENV_NINJA_SILENT_COMMAND "${_env_ninja_silent_list}")