set(BUILDMASTER_TOOLS_NINJA_SRCDIR "${BUILDMASTER_TOOLS_NINJA_SRCDIR}" PARENT_SCOPE)
set(ENV_NINJA_COMMAND ${ENV_NINJA_COMMAND} PARENT_SCOPE)
set(ENV_NINJA_SILENT_COMMAND ${ENV_NINJA_SILENT_COMMAND} PARENT_SCOPE)