file(APPEND "${BUILDMASTER_TOOLCHAIN_FILE}"
	"set(BUILDMASTER_TOOLS_NINJA_SRCDIR \"${BUILDMASTER_TOOLS_NINJA_SRCDIR}\")\n"
	"set(ENV_NINJA_COMMAND ${ENV_NINJA_COMMAND})\n"
	"set(ENV_NINJA_SILENT_COMMAND ${ENV_NINJA_SILENT_COMMAND})\n"
)
