# =============================================================================
# component/group.cmake — outline groups (no targets, no edges)
# =============================================================================
# Public: buildmaster_group, buildmaster_group_add
# Finalize walks the tree after the graph exists and records an event list:
#   banner:<id>:<depth>   then   comp:<id>
# Materialize plays that list so a member configure sits under its banner.

## @brief TRUE if `id` is a registered group.
function(_bm_group_is id out_var)
	get_property(_ids GLOBAL PROPERTY BUILDMASTER_GROUP_IDS)
	if(_ids)
		list(FIND _ids "${id}" _idx)
		if(NOT _idx EQUAL -1)
			set(${out_var} TRUE PARENT_SCOPE)
			return()
		endif()
	endif()
	set(${out_var} FALSE PARENT_SCOPE)
endfunction()

## @brief FATAL if `id` is a group (`cmd` is the public name in the message).
function(_bm_group_forbid id cmd)
	_bm_group_is("${id}" _is)
	if(_is)
		_bm_id_origin_suffix("${id}" _at)
		_bm_log_message(COMPONENT FATAL
			"${cmd}: '${id}' is a group${_at} — groups are outline only (no depend, link, or meta membership)")
	endif()
endfunction()

## @brief DFS cycle check on group → group.
function(_bm_group_cycle_visit id)
	get_property(_st GLOBAL PROPERTY BUILDMASTER_GROUP_${id}_COLOR)
	if(_st STREQUAL "gray")
		_bm_id_origin_suffix("${id}" _at)
		_bm_log_message(COMPONENT FATAL
			"buildmaster_group('${id}'): cycle in group tree${_at}")
	endif()
	if(_st STREQUAL "black")
		return()
	endif()
	set_property(GLOBAL PROPERTY BUILDMASTER_GROUP_${id}_COLOR gray)
	get_property(_mem GLOBAL PROPERTY BUILDMASTER_GROUP_${id}_MEMBERS)
	foreach(_m IN LISTS _mem)
		_bm_group_is("${_m}" _g)
		if(_g)
			_bm_group_cycle_visit("${_m}")
		endif()
	endforeach()
	set_property(GLOBAL PROPERTY BUILDMASTER_GROUP_${id}_COLOR black)
endfunction()

## @brief Append one outline event (`banner:id:depth` or `comp:id`).
function(_bm_group_event ev)
	set_property(GLOBAL APPEND PROPERTY BUILDMASTER_GROUP_EVENTS "${ev}")
endfunction()

## @brief Walk one group into the event list (no STATUS here).
function(_bm_group_walk id depth)
	_bm_group_event("banner:${id}:${depth}")
	math(EXPR _child "${depth} + 1")
	get_property(_mem GLOBAL PROPERTY BUILDMASTER_GROUP_${id}_MEMBERS)
	foreach(_m IN LISTS _mem)
		if("${_m}" STREQUAL "")
			continue()
		endif()
		_bm_group_is("${_m}" _g)
		if(_g)
			_bm_group_walk("${_m}" ${_child})
			continue()
		endif()
		set_property(GLOBAL PROPERTY BUILDMASTER_COMPONENT_${_m}_INDENT "${_child}")
		set_property(GLOBAL PROPERTY BUILDMASTER_META_${_m}_INDENT "${_child}")
		get_property(_walk GLOBAL PROPERTY BUILDMASTER_GROUP_WALK_ORDER)
		list(FIND _walk "${_m}" _idx)
		if(_idx EQUAL -1)
			set_property(GLOBAL APPEND PROPERTY BUILDMASTER_GROUP_WALK_ORDER "${_m}")
		endif()
		_bm_group_event("comp:${_m}")
	endforeach()
endfunction()

## @brief After the graph is complete: cycles, event list, leftover ids.
function(_bm_group_plan)
	_bm_log_message(COMPONENT LOWLEVEL "Entering _bm_group_plan")
	set_property(GLOBAL PROPERTY BUILDMASTER_GROUP_EVENTS "")
	get_property(_gids GLOBAL PROPERTY BUILDMASTER_GROUP_IDS)
	if(NOT _gids)
		_bm_log_message(COMPONENT LOWLEVEL "Exiting _bm_group_plan")
		return()
	endif()

	foreach(_g IN LISTS _gids)
		set_property(GLOBAL PROPERTY BUILDMASTER_GROUP_${_g}_COLOR white)
	endforeach()
	foreach(_g IN LISTS _gids)
		_bm_group_cycle_visit("${_g}")
	endforeach()

	set(_nested "")
	foreach(_g IN LISTS _gids)
		get_property(_mem GLOBAL PROPERTY BUILDMASTER_GROUP_${_g}_MEMBERS)
		foreach(_m IN LISTS _mem)
			_bm_group_is("${_m}" _isg)
			if(_isg)
				list(APPEND _nested "${_m}")
			endif()
		endforeach()
	endforeach()

	foreach(_g IN LISTS _gids)
		list(FIND _nested "${_g}" _idx)
		if(_idx EQUAL -1)
			_bm_group_walk("${_g}" 0)
		endif()
	endforeach()

	get_property(_walk GLOBAL PROPERTY BUILDMASTER_GROUP_WALK_ORDER)
	get_property(_cids GLOBAL PROPERTY BUILDMASTER_COMPONENT_IDS)
	foreach(_id IN LISTS _cids)
		list(FIND _walk "${_id}" _idx)
		if(_idx EQUAL -1)
			set_property(GLOBAL APPEND PROPERTY BUILDMASTER_GROUP_WALK_ORDER "${_id}")
			_bm_group_event("comp:${_id}")
		endif()
	endforeach()

	_bm_log_message(COMPONENT LOWLEVEL "Exiting _bm_group_plan")
endfunction()

## @brief Play banners (STATUS + indent). Components are materialized by caller.
function(_bm_group_emit_banner id depth)
	get_property(_title GLOBAL PROPERTY BUILDMASTER_GROUP_${id}_TITLE)
	if("${_title}" STREQUAL "")
		set(_title "${id}")
	endif()
	_bm_log_message(COMPONENT STATUS "${_title}" ${depth})
endfunction()

## @brief Declare an outline group.
## @param[in] _id    Unique id (not a component or meta).
## @param[in] _title Banner text (STATUS). Empty → id.
## @note Invoked only from the public macro. No INTERFACE target.
function(_bm_group_impl _id _title)
	_bm_log_message(COMPONENT LOWLEVEL "Entering _bm_group_impl")
	if("${_id}" STREQUAL "")
		_bm_log_message(COMPONENT FATAL "buildmaster_group: empty id")
	endif()
	get_property(_done GLOBAL PROPERTY BUILDMASTER_COMPONENTS_FINALIZED)
	if(_done)
		_bm_log_message(COMPONENT FATAL
			"buildmaster_group('${_id}'): called after finalize")
	endif()
	get_property(_cids GLOBAL PROPERTY BUILDMASTER_COMPONENT_IDS)
	if(_cids)
		list(FIND _cids "${_id}" _idx)
		if(NOT _idx EQUAL -1)
			_bm_id_clash_fatal("buildmaster_group" "${_id}")
		endif()
	endif()
	_bm_meta_is("${_id}" _ism)
	if(_ism)
		_bm_id_clash_fatal("buildmaster_group" "${_id}")
	endif()
	_bm_group_is("${_id}" _isg)
	if(_isg)
		_bm_id_clash_fatal("buildmaster_group" "${_id}")
	endif()
	set(_disp "${_title}")
	if("${_disp}" STREQUAL "")
		set(_disp "${_id}")
	endif()
	set_property(GLOBAL APPEND PROPERTY BUILDMASTER_GROUP_IDS "${_id}")
	set_property(GLOBAL PROPERTY BUILDMASTER_GROUP_${_id}_TITLE "${_disp}")
	_bm_graph_defer_arm()
	_bm_log_message(COMPONENT DEBUG "Registered group ${_id}")
	_bm_log_message(COMPONENT LOWLEVEL "Exiting _bm_group_impl")
endfunction()

## @brief Public group declaration (macro so origin is the caller's CMakeLists).
## @see _bm_group_impl
macro(buildmaster_group)
	if(${ARGC} LESS 1)
		_bm_log_message(COMPONENT FATAL "buildmaster_group: missing id")
	endif()
	_bm_id_stamp("${ARGV0}" group
		"${CMAKE_CURRENT_LIST_FILE}" "${CMAKE_CURRENT_LIST_LINE}")
	if(${ARGC} EQUAL 1)
		_bm_group_impl("${ARGV0}" "")
	elseif(${ARGC} EQUAL 2)
		_bm_group_impl("${ARGV0}" "${ARGV1}")
	else()
		_bm_log_message(COMPONENT FATAL
			"buildmaster_group: expected id [title]")
	endif()
endmacro()

## @brief Add members in call order (groups or components/metas).
## @param[in] _group Group id (must already exist).
## @param[in] ARGN   Member ids. Duplicates skipped. Self is FATAL.
function(_bm_group_add_impl _group)
	_bm_log_message(COMPONENT LOWLEVEL "Entering _bm_group_add_impl")
	if("${_group}" STREQUAL "")
		_bm_log_message(COMPONENT FATAL "buildmaster_group_add: empty group id")
	endif()
	if(ARGC LESS 2)
		_bm_log_message(COMPONENT FATAL
			"buildmaster_group_add: need at least one member")
	endif()
	get_property(_done GLOBAL PROPERTY BUILDMASTER_COMPONENTS_FINALIZED)
	if(_done)
		_bm_log_message(COMPONENT FATAL
			"buildmaster_group_add: called after finalize")
	endif()
	_bm_group_is("${_group}" _isg)
	if(NOT _isg)
		_bm_log_message(COMPONENT FATAL
			"buildmaster_group_add: '${_group}' is not a group")
	endif()
	get_property(_mem GLOBAL PROPERTY BUILDMASTER_GROUP_${_group}_MEMBERS)
	set(_i 1)
	while(_i LESS ARGC)
		list(GET ARGV ${_i} _m)
		math(EXPR _i "${_i} + 1")
		if("${_m}" STREQUAL "")
			continue()
		endif()
		if(_m STREQUAL "${_group}")
			_bm_log_message(COMPONENT FATAL
				"buildmaster_group_add('${_group}', '${_m}'): a group cannot contain itself")
		endif()
		if(_mem)
			list(FIND _mem "${_m}" _idx)
			if(NOT _idx EQUAL -1)
				continue()
			endif()
		endif()
		list(APPEND _mem "${_m}")
	endwhile()
	set_property(GLOBAL PROPERTY BUILDMASTER_GROUP_${_group}_MEMBERS "${_mem}")
	_bm_graph_defer_arm()
	_bm_log_message(COMPONENT DEBUG "buildmaster_group_add ${_group} members=${_mem}")
	_bm_log_message(COMPONENT LOWLEVEL "Exiting _bm_group_add_impl")
endfunction()

## @brief Public group membership (macro; origin already stamped on the group).
## @see _bm_group_add_impl
macro(buildmaster_group_add _group)
	if("${_group}" STREQUAL "")
		_bm_log_message(COMPONENT FATAL "buildmaster_group_add: missing group id")
	endif()
	_bm_group_add_impl("${_group}" ${ARGN})
endmacro()
