if(NOT BUILDMASTER_CONFIGURED)
	set(BUILDMASTER_COMPONENT_SRCDIR "${CMAKE_CURRENT_LIST_DIR}")
	set(BUILDMASTER_COMPONENT_TEMPLATEDIR
		"${CMAKE_CURRENT_LIST_DIR}/templates")
	set(BUILDMASTER_SCRIPTS_COMPONENTDIR "${BUILDMASTER_SCRIPTSDIR}/component")
	set(BUILDMASTER_SCRIPTS_HOOK_DIR "${BUILDMASTER_SCRIPTSDIR}/hooks")
	file(MAKE_DIRECTORY "${BUILDMASTER_SCRIPTS_COMPONENTDIR}")
	file(MAKE_DIRECTORY "${BUILDMASTER_SCRIPTS_HOOK_DIR}")

	# Update out part of the toolchain file
	include("${CMAKE_CURRENT_LIST_DIR}/update_toolchain.cmake")
endif()
