if(NOT BUILDMASTER_CONFIGURED)
	set(BUILDMASTER_COMPONENT_SRCDIR "${CMAKE_CURRENT_LIST_DIR}")
	set(BUILDMASTER_SCRIPTS_COMPONENTDIR "${BUILDMASTER_SCRIPTSDIR}/component")
	file(MAKE_DIRECTORY "${BUILDMASTER_SCRIPTS_COMPONENTDIR}")

	# Update out part of the toolchain file
	include("${CMAKE_CURRENT_LIST_DIR}/update_toolchain.cmake")
endif()