set(BUILDMASTER_COMPONENT_SRCDIR "${BUILDMASTER_COMPONENT_SRCDIR}" PARENT_SCOPE)
set(BUILDMASTER_COMPONENT_TEMPLATEDIR "${BUILDMASTER_COMPONENT_TEMPLATEDIR}" PARENT_SCOPE)
set(BUILDMASTER_SCRIPTS_COMPONENTDIR "${BUILDMASTER_SCRIPTS_COMPONENTDIR}" PARENT_SCOPE)
set(BUILDMASTER_SCRIPTS_HOOK_DIR "${BUILDMASTER_SCRIPTS_HOOK_DIR}" PARENT_SCOPE)
