_bm_tc_export(BUILDMASTER_COMPONENT_SRCDIR "${BUILDMASTER_COMPONENT_SRCDIR}")
_bm_tc_export(BUILDMASTER_COMPONENT_TEMPLATEDIR "${BUILDMASTER_COMPONENT_TEMPLATEDIR}")
_bm_tc_export(BUILDMASTER_SCRIPTS_COMPONENTDIR "${BUILDMASTER_SCRIPTS_COMPONENTDIR}")