file(APPEND "${BUILDMASTER_TOOLCHAIN_FILE}"
	"set(BUILDMASTER_COMPONENT_SRCDIR \"${BUILDMASTER_COMPONENT_SRCDIR}\")\n"
	"set(BUILDMASTER_SCRIPTS_COMPONENTDIR \"${BUILDMASTER_SCRIPTS_COMPONENTDIR}\")\n"
)
