# =============================================================================
# Meson native files (one per toolchain profile)
# -----------------------------------------------------------------------------
# Written under ${BUILDMASTER_SCRIPTSDIR}/meson/native_<profile>.ini so nested
# Meson setups can use --native-file and pick up ccache/sccache + the profile
# compilers the same way CMake uses CMAKE_*_COMPILER_LAUNCHER.
#
# Variables set (and exported into the toolchain dump):
#   BUILDMASTER_MESON_NATIVE_FILE           - parent / default job compilers
#   BUILDMASTER_MESON_NATIVE_FILE_<name>    - per known profile (gcc, msvc, …)
# =============================================================================

include_guard(GLOBAL)

## @brief Quote a filesystem path for a Meson native-file string list entry.
## @param[out] out_var Parent-scope variable receiving a single-quoted path.
## @param[in] path Path to quote (backslashes normalized to '/').
function(buildmaster_meson_native_quote out_var path)
	string(REPLACE "\\" "/" path "${path}")
	string(REPLACE "'" "\\'" path "${path}")
	set(${out_var} "'${path}'" PARENT_SCOPE)
endfunction()

## @brief Build one Meson [binaries] assignment line.
## @param[out] out_var Parent-scope variable receiving e.g.
##            `c = ['sccache', 'cl']` or `c = ['cl']`.
## @param[in] name Binary key (`c`, `cpp`, …).
## @param[in] compiler Compiler path or short name (must not be empty).
## @param[in] launcher Optional ccache/sccache path or name; empty = no launcher.
function(buildmaster_meson_native_bin_line out_var name compiler launcher)
	if(compiler STREQUAL "")
		set(${out_var} "" PARENT_SCOPE)
		return()
	endif()
	buildmaster_meson_native_quote(_comp "${compiler}")
	if(NOT launcher STREQUAL "")
		buildmaster_meson_native_quote(_launch "${launcher}")
		set(${out_var} "${name} = [${_launch}, ${_comp}]" PARENT_SCOPE)
	else()
		set(${out_var} "${name} = [${_comp}]" PARENT_SCOPE)
	endif()
endfunction()

## @brief Resolve the active compiler launcher (ccache or sccache).
## @param[out] out_var Parent-scope variable; empty when no launcher is set.
## @note Prefers CMAKE_C_COMPILER_LAUNCHER, then CMAKE_CXX_COMPILER_LAUNCHER,
##       then the matching ENV values. Uses the first list element when set.
function(buildmaster_meson_native_resolve_launcher out_var)
	set(_l "")
	if(NOT "${CMAKE_C_COMPILER_LAUNCHER}" STREQUAL "")
		list(GET CMAKE_C_COMPILER_LAUNCHER 0 _l)
	elseif(NOT "${CMAKE_CXX_COMPILER_LAUNCHER}" STREQUAL "")
		list(GET CMAKE_CXX_COMPILER_LAUNCHER 0 _l)
	elseif(DEFINED ENV{CMAKE_C_COMPILER_LAUNCHER} AND NOT "$ENV{CMAKE_C_COMPILER_LAUNCHER}" STREQUAL "")
		set(_l "$ENV{CMAKE_C_COMPILER_LAUNCHER}")
	elseif(DEFINED ENV{CMAKE_CXX_COMPILER_LAUNCHER} AND NOT "$ENV{CMAKE_CXX_COMPILER_LAUNCHER}" STREQUAL "")
		set(_l "$ENV{CMAKE_CXX_COMPILER_LAUNCHER}")
	endif()
	set(${out_var} "${_l}" PARENT_SCOPE)
endfunction()

## @brief Write (or overwrite) one Meson native file for a profile key.
## @param[in] profile_key `default` or a known toolchain name (`msvc`, …).
## @param[in] c_compiler C compiler path or short name.
## @param[in] cxx_compiler C++ compiler path or short name (falls back to C).
## @param[in] ARGN Optional `LAUNCHER <name-or-path>` override.
## @note Sets BUILDMASTER_MESON_NATIVE_FILE or BUILDMASTER_MESON_NATIVE_FILE_<key>
##       in the parent scope and registers them in the toolchain export registry.
function(buildmaster_write_meson_native_file profile_key c_compiler cxx_compiler)
	cmake_parse_arguments(ARG "" "LAUNCHER" "" ${ARGN})

	if(NOT DEFINED BUILDMASTER_SCRIPTSDIR OR BUILDMASTER_SCRIPTSDIR STREQUAL "")
		message(FATAL_ERROR
			"[BuildMaster] BUILDMASTER_SCRIPTSDIR is required to write Meson native files")
	endif()

	set(_dir "${BUILDMASTER_SCRIPTSDIR}/meson")
	file(MAKE_DIRECTORY "${_dir}")

	string(STRIP "${profile_key}" _key)
	string(TOLOWER "${_key}" _key)
	if(_key STREQUAL "" OR _key STREQUAL "default")
		set(_filename "native_default.ini")
		set(_var "BUILDMASTER_MESON_NATIVE_FILE")
		set(_label "default")
	else()
		set(_filename "native_${_key}.ini")
		set(_var "BUILDMASTER_MESON_NATIVE_FILE_${_key}")
		set(_label "${_key}")
	endif()

	set(_path "${_dir}/${_filename}")
	normalize_cmake_path(_path "${_path}")

	set(_launcher "")
	if(DEFINED ARG_LAUNCHER)
		set(_launcher "${ARG_LAUNCHER}")
	else()
		buildmaster_meson_native_resolve_launcher(_launcher)
	endif()

	if(cxx_compiler STREQUAL "")
		set(cxx_compiler "${c_compiler}")
	endif()
	if(c_compiler STREQUAL "")
		set(c_compiler "${cxx_compiler}")
	endif()

	buildmaster_meson_native_bin_line(_line_c   "c"   "${c_compiler}"   "${_launcher}")
	buildmaster_meson_native_bin_line(_line_cpp "cpp" "${cxx_compiler}" "${_launcher}")

	set(_content "# Auto-generated by StormByte-BuildMaster (toolchain) — do not edit\n")
	string(APPEND _content "# profile: ${_label}\n")
	string(APPEND _content "[binaries]\n")
	if(NOT _line_c STREQUAL "")
		string(APPEND _content "${_line_c}\n")
	endif()
	if(NOT _line_cpp STREQUAL "")
		string(APPEND _content "${_line_cpp}\n")
	endif()

	file(WRITE "${_path}" "${_content}")

	set(${_var} "${_path}" PARENT_SCOPE)
	buildmaster_toolchain_export("${_var}" "${_path}")

	message(STATUS "[toolchain] Meson native file (${_label}) → ${_path}")
endfunction()

## @brief Resolve which native-file path a Meson component should use.
## @param[out] out_var Parent-scope variable receiving the path (may be empty).
## @param[in] ARGN Optional `TOOLCHAIN <name>`. Empty = this process's compiler
##            family (`CMAKE_C_COMPILER_ID` / clang-cl), then the default file.
function(buildmaster_get_meson_native_file out_var)
	cmake_parse_arguments(ARG "" "TOOLCHAIN" "" ${ARGN})
	set(_path "")
	set(_key "")

	if(DEFINED ARG_TOOLCHAIN AND NOT ARG_TOOLCHAIN STREQUAL "")
		string(TOLOWER "${ARG_TOOLCHAIN}" _key)
	else()
		if(WIN32)
			if(CMAKE_C_COMPILER MATCHES "clang-cl" OR
				(CMAKE_C_COMPILER_ID STREQUAL "Clang" AND
					CMAKE_C_COMPILER_FRONTEND_VARIANT STREQUAL "MSVC"))
				set(_key "clang-cl")
			elseif(CMAKE_C_COMPILER_ID STREQUAL "MSVC")
				set(_key "msvc")
			endif()
		else()
			if(CMAKE_C_COMPILER_ID STREQUAL "GNU")
				set(_key "gcc")
			elseif(CMAKE_C_COMPILER_ID STREQUAL "Clang")
				set(_key "clang")
			endif()
		endif()
	endif()

	if(NOT _key STREQUAL "")
		if(DEFINED BUILDMASTER_MESON_NATIVE_FILE_${_key}
				AND NOT BUILDMASTER_MESON_NATIVE_FILE_${_key} STREQUAL "")
			set(_path "${BUILDMASTER_MESON_NATIVE_FILE_${_key}}")
		endif()
	endif()
	if(_path STREQUAL "" AND DEFINED BUILDMASTER_MESON_NATIVE_FILE)
		set(_path "${BUILDMASTER_MESON_NATIVE_FILE}")
	endif()
	set(${out_var} "${_path}" PARENT_SCOPE)
endfunction()

## @brief Generate native files for the parent job and every known profile.
## @note Called once when the toolchain module finishes initializing (primary
##       bootstrap). Profile compilers use short names from profiles/*.cmake;
##       MSVC-style tools are resolved to absolute paths when possible so Ninja
##       and Meson do not treat bare `cl` as relative to the build dir.
##       Safe to call again; files are overwritten.
function(buildmaster_init_meson_native_files)
	if(NOT DEFINED BUILDMASTER_SCRIPTSDIR OR BUILDMASTER_SCRIPTSDIR STREQUAL "")
		message(STATUS "[toolchain] Skipping Meson native files (BUILDMASTER_SCRIPTSDIR unset)")
		return()
	endif()

	buildmaster_meson_native_resolve_launcher(_launch)

	# Parent / default: whatever the host project is already using
	set(_c "${CMAKE_C_COMPILER}")
	set(_cxx "${CMAKE_CXX_COMPILER}")
	if(_c STREQUAL "" AND NOT _cxx STREQUAL "")
		set(_c "${_cxx}")
	endif()
	if(_cxx STREQUAL "" AND NOT _c STREQUAL "")
		set(_cxx "${_c}")
	endif()

	if(NOT _c STREQUAL "")
		buildmaster_write_meson_native_file("default" "${_c}" "${_cxx}" LAUNCHER "${_launch}")
		set(BUILDMASTER_MESON_NATIVE_FILE "${BUILDMASTER_MESON_NATIVE_FILE}" PARENT_SCOPE)
	else()
		message(STATUS "[toolchain] Skipping default Meson native file (compilers not set yet)")
	endif()

	# One file per known profile (platform-filtered)
	if(NOT DEFINED BUILDMASTER_KNOWN_TOOLCHAINS)
		return()
	endif()

	foreach(_prof IN LISTS BUILDMASTER_KNOWN_TOOLCHAINS)
		if(_prof STREQUAL "msvc" OR _prof STREQUAL "clang-cl")
			if(NOT WIN32)
				continue()
			endif()
		endif()
		if(_prof STREQUAL "gcc" OR _prof STREQUAL "clang")
			if(WIN32)
				continue()
			endif()
		endif()

		set(_profile_file "${BUILDMASTER_TOOLCHAIN_PROFILES_DIR}/${_prof}.cmake")
		if(NOT EXISTS "${_profile_file}")
			continue()
		endif()

		# Load profile into this function scope only
		include("${_profile_file}")

		set(_pc "${BM_TC_C_COMPILER}")
		set(_px "${BM_TC_CXX_COMPILER}")
		if(_px STREQUAL "")
			set(_px "${_pc}")
		endif()

		# Prefer absolute paths for MSVC driver tools
		if(_prof STREQUAL "msvc" OR _prof STREQUAL "clang-cl")
			if(COMMAND buildmaster_resolve_msvc_tool)
				buildmaster_resolve_msvc_tool(_pc_res "${_pc}")
				buildmaster_resolve_msvc_tool(_px_res "${_px}")
				set(_pc "${_pc_res}")
				set(_px "${_px_res}")
			endif()
		else()
			# Unix: resolve via find_program when not absolute
			if(NOT IS_ABSOLUTE "${_pc}")
				find_program(_bm_nc NAMES "${_pc}" "${_pc}.exe")
				if(_bm_nc)
					normalize_cmake_path(_pc "${_bm_nc}")
				endif()
				unset(_bm_nc CACHE)
			endif()
			if(NOT IS_ABSOLUTE "${_px}")
				find_program(_bm_nx NAMES "${_px}" "${_px}.exe")
				if(_bm_nx)
					normalize_cmake_path(_px "${_bm_nx}")
				endif()
				unset(_bm_nx CACHE)
			endif()
		endif()

		if(NOT _pc STREQUAL "")
			buildmaster_write_meson_native_file("${_prof}" "${_pc}" "${_px}" LAUNCHER "${_launch}")
			set(BUILDMASTER_MESON_NATIVE_FILE_${_prof}
				"${BUILDMASTER_MESON_NATIVE_FILE_${_prof}}" PARENT_SCOPE)
		endif()
	endforeach()
endfunction()
