set(BUILDMASTER_TOOLCHAIN_SRCDIR "${BUILDMASTER_TOOLCHAIN_SRCDIR}" PARENT_SCOPE)
set(BUILDMASTER_TOOLCHAIN_PROFILES_DIR "${BUILDMASTER_TOOLCHAIN_PROFILES_DIR}" PARENT_SCOPE)
set(BUILDMASTER_KNOWN_TOOLCHAINS "${BUILDMASTER_KNOWN_TOOLCHAINS}" PARENT_SCOPE)
