set(BUILDMASTER_TOOLCHAIN_SRCDIR "${BUILDMASTER_TOOLCHAIN_SRCDIR}" PARENT_SCOPE)
set(BUILDMASTER_TOOLCHAIN_PROFILES_DIR "${BUILDMASTER_TOOLCHAIN_PROFILES_DIR}" PARENT_SCOPE)
set(BUILDMASTER_KNOWN_TOOLCHAINS "${BUILDMASTER_KNOWN_TOOLCHAINS}" PARENT_SCOPE)

if(DEFINED BUILDMASTER_MESON_NATIVE_FILE)
	set(BUILDMASTER_MESON_NATIVE_FILE "${BUILDMASTER_MESON_NATIVE_FILE}" PARENT_SCOPE)
endif()
foreach(_bm_tc_prof IN ITEMS gcc clang clang-cl msvc)
	if(DEFINED BUILDMASTER_MESON_NATIVE_FILE_${_bm_tc_prof})
		set(BUILDMASTER_MESON_NATIVE_FILE_${_bm_tc_prof}
			"${BUILDMASTER_MESON_NATIVE_FILE_${_bm_tc_prof}}" PARENT_SCOPE)
	endif()
endforeach()

set(CMAKE_C_LINK_EXECUTABLE "${CMAKE_C_LINK_EXECUTABLE}" PARENT_SCOPE)
set(CMAKE_CXX_LINK_EXECUTABLE "${CMAKE_CXX_LINK_EXECUTABLE}" PARENT_SCOPE)
