file(APPEND "${BUILDMASTER_TOOLCHAIN_FILE}"
	"set(BUILDMASTER_TOOLCHAIN_SRCDIR \"${BUILDMASTER_TOOLCHAIN_SRCDIR}\")\n"
	"set(BUILDMASTER_TOOLCHAIN_PROFILES_DIR \"${BUILDMASTER_TOOLCHAIN_PROFILES_DIR}\")\n"
	"set(BUILDMASTER_KNOWN_TOOLCHAINS \"${BUILDMASTER_KNOWN_TOOLCHAINS}\")\n"
)
